// src/lib/trading-data.ts
// Comprehensive stock data for Indian markets including:
// - Nifty 50 stocks (50 stocks)
// - Sensex 30 stocks (30 stocks - official index)
// - Bank Nifty stocks (12 stocks - official index)
// - Nifty Next 50 stocks (50 stocks)
// - Finnifty stocks (50 stocks)
// - BSE Midcap stocks (40 stocks)
// - BSE Small Cap stocks (50 stocks)
// - Additional Popular stocks (25 stocks)
// Total: ~300+ unique stocks across major indices
// Ensures complete coverage of NIFTY 50, SENSEX 30, BANK NIFTY, NIFTY NEXT 50, and FINNIFTY

export const nifty50Stocks = [
  { ticker: 'ADANIENT', name: 'Adani Enterprises Ltd.', price: 2330.1, change: 1.2, marketCap: '2.65T', industry: 'Metals & Mining', indices: ['NIFTY 50'] },
  { ticker: 'ADANIPORTS', name: 'Adani Ports and Special Economic Zone Ltd.', price: 1357.55, change: -0.5, marketCap: '2.93T', industry: 'Transportation & Logistics', indices: ['NIFTY 50', 'SENSEX 30'] },
  { ticker: 'APOLLOHOSP', name: 'Apollo Hospitals Enterprise Ltd.', price: 5934.3, change: 2.1, marketCap: '852B', industry: 'Healthcare', indices: ['NIFTY 50'] },
  { ticker: 'ASIANPAINT', name: 'Asian Paints Ltd.', price: 2886.5, change: -1.1, marketCap: '2.77T', industry: 'Chemicals', indices: ['NIFTY 50', 'SENSEX 30'] },
  { ticker: 'AXISBANK', name: 'Axis Bank Ltd.', price: 1047.85, change: 0.8, marketCap: '3.22T', industry: 'Banking', indices: ['NIFTY 50', 'SENSEX 30', 'BANK NIFTY'] },
  { ticker: 'BAJAJ-AUTO', name: 'Bajaj Auto Ltd.', price: 7284.8, change: 1.5, marketCap: '2.04T', industry: 'Automobile', indices: ['NIFTY 50'] },
  { ticker: 'BAJFINANCE', name: 'Bajaj Finance Ltd.', price: 7234.25, change: -2.3, marketCap: '4.48T', industry: 'Financial Services', indices: ['NIFTY 50', 'SENSEX 30'] },
  { ticker: 'BAJAJFINSV', name: 'Bajaj Finserv Ltd.', price: 1623.4, change: 0.2, marketCap: '2.58T', industry: 'Financial Services', indices: ['NIFTY 50', 'SENSEX 30'] },
  { ticker: 'BPCL', name: 'Bharat Petroleum Corporation Ltd.', price: 605.3, change: -0.9, marketCap: '1.31T', industry: 'Oil & Gas', indices: ['NIFTY 50', 'NIFTY NEXT 50'] },
  { ticker: 'BHARTIARTL', name: 'Bharti Airtel Ltd.', price: 1198.4, change: 1.8, marketCap: '6.8T', industry: 'Telecommunications', indices: ['NIFTY 50', 'SENSEX 30'] },
  { ticker: 'BRITANNIA', name: 'Britannia Industries Ltd.', price: 4899.75, change: 0.4, marketCap: '1.18T', industry: 'FMCG', indices: ['NIFTY 50', 'NIFTY NEXT 50'] },
  { ticker: 'CIPLA', name: 'Cipla Ltd.', price: 1304.85, change: -1.4, marketCap: '1.05T', industry: 'Healthcare', indices: ['NIFTY 50'] },
  { ticker: 'COALINDIA', name: 'Coal India Ltd.', price: 433.8, change: 2.5, marketCap: '2.67T', industry: 'Metals & Mining', indices: ['NIFTY 50'] },
  { ticker: 'DIVISLAB', name: 'Divi\'s Laboratories Ltd.', price: 3719.9, change: 0.1, marketCap: '988B', industry: 'Healthcare', indices: ['NIFTY 50', 'NIFTY NEXT 50'] },
  { ticker: 'DRREDDY', name: 'Dr. Reddy\'s Laboratories Ltd.', price: 5802.4, change: -0.7, marketCap: '968B', industry: 'Healthcare', indices: ['NIFTY 50'] },
  { ticker: 'EICHERMOT', name: 'Eicher Motors Ltd.', price: 3824.2, change: 1.1, marketCap: '1.05T', industry: 'Automobile', indices: ['NIFTY 50'] },
  { ticker: 'GRASIM', name: 'Grasim Industries Ltd.', price: 2186.4, change: 0.9, marketCap: '1.44T', industry: 'Cement & Construction Materials', indices: ['NIFTY 50'] },
  { ticker: 'HCLTECH', name: 'HCL Technologies Ltd.', price: 1642.4, change: -1.2, marketCap: '4.45T', industry: 'IT', indices: ['NIFTY 50', 'SENSEX 30'] },
  { ticker: 'HDFCBANK', name: 'HDFC Bank Ltd.', price: 1447.5, change: 2.2, marketCap: '11T', industry: 'Banking', indices: ['NIFTY 50', 'SENSEX 30', 'BANK NIFTY'] },
  { ticker: 'HDFCLIFE', name: 'HDFC Life Insurance Company Ltd.', price: 619.0, change: -0.3, marketCap: '1.33T', industry: 'Insurance', indices: ['NIFTY 50'] },
  { ticker: 'HEROMOTOCO', name: 'Hero MotoCorp Ltd.', price: 4509.3, change: 1.3, marketCap: '901B', industry: 'Automobile', indices: ['NIFTY 50'] },
  { ticker: 'HINDALCO', name: 'Hindalco Industries Ltd.', price: 559.8, change: -2.0, marketCap: '1.26T', industry: 'Metals & Mining', indices: ['NIFTY 50'] },
  { ticker: 'HINDUNILVR', name: 'Hindustan Unilever Ltd.', price: 2420.0, change: 0.6, marketCap: '5.68T', industry: 'FMCG', indices: ['NIFTY 50', 'SENSEX 30'] },
  { ticker: 'ICICIBANK', name: 'ICICI Bank Ltd.', price: 1069.95, change: 1.4, marketCap: '7.52T', industry: 'Banking', indices: ['NIFTY 50', 'SENSEX 30', 'BANK NIFTY'] },
  { ticker: 'INDUSINDBK', name: 'IndusInd Bank Ltd.', price: 1495.2, change: -1.8, marketCap: '1.16T', industry: 'Banking', indices: ['NIFTY 50', 'SENSEX 30', 'BANK NIFTY'] },
  { ticker: 'INFY', name: 'Infosys Ltd.', price: 1665.0, change: 0.3, marketCap: '6.91T', industry: 'IT', indices: ['NIFTY 50', 'SENSEX 30'] },
  { ticker: 'ITC', name: 'ITC Ltd.', price: 429.25, change: -0.1, marketCap: '5.36T', industry: 'FMCG', indices: ['NIFTY 50', 'SENSEX 30'] },
  { ticker: 'JSWSTEEL', name: 'JSW Steel Ltd.', price: 818.15, change: 2.3, marketCap: '2.0T', industry: 'Metals & Mining', indices: ['NIFTY 50', 'SENSEX 30'] },
  { ticker: 'KOTAKBANK', name: 'Kotak Mahindra Bank Ltd.', price: 1774.8, change: -1.5, marketCap: '3.53T', industry: 'Banking', indices: ['NIFTY 50', 'SENSEX 30', 'BANK NIFTY'] },
  { ticker: 'LTIM', name: 'LTIMindtree Ltd.', price: 5126.3, change: 0.5, marketCap: '1.52T', industry: 'IT', indices: ['NIFTY 50', 'NIFTY NEXT 50'] },
  { ticker: 'LT', name: 'Larsen & Toubro Ltd.', price: 3418.05, change: 1.9, marketCap: '4.71T', industry: 'Engineering & Construction', indices: ['NIFTY 50', 'SENSEX 30'] },
  { ticker: 'M&M', name: 'Mahindra & Mahindra Ltd.', price: 1819.1, change: -0.8, marketCap: '2.26T', industry: 'Automobile', indices: ['NIFTY 50', 'SENSEX 30'] },
  { ticker: 'MARUTI', name: 'Maruti Suzuki India Ltd.', price: 11489.9, change: 2.4, marketCap: '3.61T', industry: 'Automobile', indices: ['NIFTY 50', 'SENSEX 30'] },
  { ticker: 'NESTLEIND', name: 'Nestle India Ltd.', price: 2548.1, change: 0.0, marketCap: '2.46T', industry: 'FMCG', indices: ['NIFTY 50', 'SENSEX 30'] },
  { ticker: 'NTPC', name: 'NTPC Ltd.', price: 337.8, change: -1.3, marketCap: '3.28T', industry: 'Power', indices: ['NIFTY 50', 'SENSEX 30'] },
  { ticker: 'ONGC', name: 'Oil & Natural Gas Corporation Ltd.', price: 268.4, change: 1.6, marketCap: '3.38T', industry: 'Oil & Gas', indices: ['NIFTY 50'] },
  { ticker: 'POWERGRID', name: 'Power Grid Corporation of India Ltd.', price: 275.5, change: 0.7, marketCap: '2.56T', industry: 'Power', indices: ['NIFTY 50', 'SENSEX 30'] },
  { ticker: 'RELIANCE', name: 'Reliance Industries Ltd.', price: 2959.8, change: -0.2, marketCap: '20.02T', industry: 'Oil & Gas', indices: ['NIFTY 50', 'SENSEX 30'] },
  { ticker: 'SBILIFE', name: 'SBI Life Insurance Company Ltd.', price: 1459.4, change: 1.0, marketCap: '1.46T', industry: 'Insurance', indices: ['NIFTY 50'] },
  { ticker: 'SBIN', name: 'State Bank of India', price: 761.6, change: -1.1, marketCap: '6.8T', industry: 'Banking', indices: ['NIFTY 50', 'SENSEX 30', 'BANK NIFTY'] },
  { ticker: 'SUNPHARMA', name: 'Sun Pharmaceutical Industries Ltd.', price: 1493.7, change: 2.0, marketCap: '3.58T', industry: 'Healthcare', indices: ['NIFTY 50'] },
  { ticker: 'TATACONSUM', name: 'Tata Consumer Products Ltd.', price: 1121.25, change: -0.4, marketCap: '1.05T', industry: 'FMCG', indices: ['NIFTY 50'] },
  { ticker: 'TATAMOTORS', name: 'Tata Motors Ltd.', price: 978.8, change: 0.6, marketCap: '3.25T', industry: 'Automobile', indices: ['NIFTY 50', 'SENSEX 30'] },
  { ticker: 'TATASTEEL', name: 'Tata Steel Ltd.', price: 153.2, change: -1.7, marketCap: '1.91T', industry: 'Metals & Mining', indices: ['NIFTY 50', 'SENSEX 30'] },
  { ticker: 'TCS', name: 'Tata Consultancy Services Ltd.', price: 4134.8, change: 1.2, marketCap: '15T', industry: 'IT', indices: ['NIFTY 50', 'SENSEX 30'] },
  { ticker: 'TECHM', name: 'Tech Mahindra Ltd.', price: 1293.0, change: -0.6, marketCap: '1.26T', industry: 'IT', indices: ['NIFTY 50'] },
  { ticker: 'TITAN', name: 'Titan Company Ltd.', price: 3632.5, change: 2.1, marketCap: '3.23T', industry: 'Consumer Goods', indices: ['NIFTY 50', 'SENSEX 30'] },
  { ticker: 'ULTRACEMCO', name: 'UltraTech Cement Ltd.', price: 9946.5, change: -1.0, marketCap: '2.87T', industry: 'Cement & Construction Materials', indices: ['NIFTY 50', 'SENSEX 30'] },
  { ticker: 'WIPRO', name: 'Wipro Ltd.', price: 514.8, change: 0.8, marketCap: '2.69T', industry: 'IT', indices: ['NIFTY 50', 'SENSEX 30'] },
];

export const sensexStocks = [
  { ticker: 'RELIANCE', name: 'Reliance Industries Ltd.', price: 2959.8, change: -0.2, marketCap: '20.02T', industry: 'Oil & Gas', indices: ['SENSEX 30', 'NIFTY 50'] },
  { ticker: 'TCS', name: 'Tata Consultancy Services Ltd.', price: 4134.8, change: 1.2, marketCap: '15T', industry: 'IT', indices: ['SENSEX 30', 'NIFTY 50'] },
  { ticker: 'HDFCBANK', name: 'HDFC Bank Ltd.', price: 1447.5, change: 2.2, marketCap: '11T', industry: 'Banking', indices: ['SENSEX 30', 'NIFTY 50', 'BANK NIFTY'] },
  { ticker: 'ICICIBANK', name: 'ICICI Bank Ltd.', price: 1069.95, change: 1.4, marketCap: '7.52T', industry: 'Banking', indices: ['SENSEX 30', 'NIFTY 50', 'BANK NIFTY'] },
  { ticker: 'INFY', name: 'Infosys Ltd.', price: 1665.0, change: 0.3, marketCap: '6.91T', industry: 'IT', indices: ['SENSEX 30', 'NIFTY 50'] },
  { ticker: 'ITC', name: 'ITC Ltd.', price: 429.25, change: -0.1, marketCap: '5.36T', industry: 'FMCG', indices: ['SENSEX 30', 'NIFTY 50'] },
  { ticker: 'HINDUNILVR', name: 'Hindustan Unilever Ltd.', price: 2420.0, change: 0.6, marketCap: '5.68T', industry: 'FMCG', indices: ['SENSEX 30', 'NIFTY 50'] },
  { ticker: 'HCLTECH', name: 'HCL Technologies Ltd.', price: 1642.4, change: -1.2, marketCap: '4.45T', industry: 'IT', indices: ['SENSEX 30', 'NIFTY 50'] },
  { ticker: 'BAJFINANCE', name: 'Bajaj Finance Ltd.', price: 7234.25, change: -2.3, marketCap: '4.48T', industry: 'Financial Services', indices: ['SENSEX 30', 'NIFTY 50'] },
  { ticker: 'LT', name: 'Larsen & Toubro Ltd.', price: 3418.05, change: 1.9, marketCap: '4.71T', industry: 'Engineering & Construction', indices: ['SENSEX 30', 'NIFTY 50'] },
  { ticker: 'AXISBANK', name: 'Axis Bank Ltd.', price: 1047.85, change: 0.8, marketCap: '3.22T', industry: 'Banking', indices: ['SENSEX 30', 'NIFTY 50', 'BANK NIFTY'] },
  { ticker: 'KOTAKBANK', name: 'Kotak Mahindra Bank Ltd.', price: 1774.8, change: -1.5, marketCap: '3.53T', industry: 'Banking', indices: ['SENSEX 30', 'NIFTY 50', 'BANK NIFTY'] },
  { ticker: 'SUNPHARMA', name: 'Sun Pharmaceutical Industries Ltd.', price: 1493.7, change: 2.0, marketCap: '3.58T', industry: 'Healthcare', indices: ['SENSEX 30', 'NIFTY 50'] },
  { ticker: 'TATAMOTORS', name: 'Tata Motors Ltd.', price: 978.8, change: 0.6, marketCap: '3.25T', industry: 'Automobile', indices: ['SENSEX 30', 'NIFTY 50'] },
  { ticker: 'MARUTI', name: 'Maruti Suzuki India Ltd.', price: 11489.9, change: 2.4, marketCap: '3.61T', industry: 'Automobile', indices: ['SENSEX 30', 'NIFTY 50'] },
  { ticker: 'TATASTEEL', name: 'Tata Steel Ltd.', price: 153.2, change: -1.7, marketCap: '1.91T', industry: 'Metals & Mining', indices: ['SENSEX 30', 'NIFTY 50'] },
  { ticker: 'JSWSTEEL', name: 'JSW Steel Ltd.', price: 818.15, change: 2.3, marketCap: '2.0T', industry: 'Metals & Mining', indices: ['SENSEX 30', 'NIFTY 50'] },
  { ticker: 'ADANIPORTS', name: 'Adani Ports and Special Economic Zone Ltd.', price: 1357.55, change: -0.5, marketCap: '2.93T', industry: 'Transportation & Logistics', indices: ['SENSEX 30', 'NIFTY 50'] },
  { ticker: 'ASIANPAINT', name: 'Asian Paints Ltd.', price: 2886.5, change: -1.1, marketCap: '2.77T', industry: 'Chemicals', indices: ['SENSEX 30', 'NIFTY 50'] },
  { ticker: 'BHARTIARTL', name: 'Bharti Airtel Ltd.', price: 1198.4, change: 1.8, marketCap: '6.8T', industry: 'Telecommunications', indices: ['SENSEX 30', 'NIFTY 50'] },
  { ticker: 'NESTLEIND', name: 'Nestle India Ltd.', price: 2548.1, change: 0.0, marketCap: '2.46T', industry: 'FMCG', indices: ['SENSEX 30', 'NIFTY 50'] },
  { ticker: 'POWERGRID', name: 'Power Grid Corporation of India Ltd.', price: 275.5, change: 0.7, marketCap: '2.56T', industry: 'Power', indices: ['SENSEX 30', 'NIFTY 50'] },
  { ticker: 'NTPC', name: 'NTPC Ltd.', price: 337.8, change: -1.3, marketCap: '3.28T', industry: 'Power', indices: ['SENSEX 30', 'NIFTY 50'] },
  { ticker: 'INDUSINDBK', name: 'IndusInd Bank Ltd.', price: 1495.2, change: -1.8, marketCap: '1.16T', industry: 'Banking', indices: ['SENSEX 30', 'NIFTY 50', 'BANK NIFTY'] },
  { ticker: 'SBIN', name: 'State Bank of India', price: 761.6, change: -1.1, marketCap: '6.8T', industry: 'Banking', indices: ['SENSEX 30', 'NIFTY 50', 'BANK NIFTY'] },
  { ticker: 'M&M', name: 'Mahindra & Mahindra Ltd.', price: 1819.1, change: -0.8, marketCap: '2.26T', industry: 'Automobile', indices: ['SENSEX 30', 'NIFTY 50'] },
  { ticker: 'ULTRACEMCO', name: 'UltraTech Cement Ltd.', price: 9946.5, change: -1.0, marketCap: '2.87T', industry: 'Cement & Construction Materials', indices: ['SENSEX 30', 'NIFTY 50'] },
  { ticker: 'TITAN', name: 'Titan Company Ltd.', price: 3632.5, change: 2.1, marketCap: '3.23T', industry: 'Consumer Goods', indices: ['SENSEX 30', 'NIFTY 50'] },
  { ticker: 'WIPRO', name: 'Wipro Ltd.', price: 514.8, change: 0.8, marketCap: '2.69T', industry: 'IT', indices: ['SENSEX 30', 'NIFTY 50'] },
];

export const bankNiftyStocks = [
  { ticker: 'HDFCBANK', name: 'HDFC Bank Ltd.', price: 1447.5, change: 2.2, marketCap: '11T', industry: 'Financial Services', indices: ['BANK NIFTY', 'NIFTY 50', 'SENSEX 30', 'FINNIFTY'] },
  { ticker: 'ICICIBANK', name: 'ICICI Bank Ltd.', price: 1069.95, change: 1.4, marketCap: '7.52T', industry: 'Financial Services', indices: ['BANK NIFTY', 'NIFTY 50', 'SENSEX 30', 'FINNIFTY'] },
  { ticker: 'AXISBANK', name: 'Axis Bank Ltd.', price: 1047.85, change: 0.8, marketCap: '3.22T', industry: 'Financial Services', indices: ['BANK NIFTY', 'NIFTY 50', 'SENSEX 30', 'FINNIFTY'] },
  { ticker: 'KOTAKBANK', name: 'Kotak Mahindra Bank Ltd.', price: 1774.8, change: -1.5, marketCap: '3.53T', industry: 'Financial Services', indices: ['BANK NIFTY', 'NIFTY 50', 'SENSEX 30', 'FINNIFTY'] },
  { ticker: 'SBIN', name: 'State Bank of India', price: 761.6, change: -1.1, marketCap: '6.8T', industry: 'Financial Services', indices: ['BANK NIFTY', 'NIFTY 50', 'SENSEX 30', 'FINNIFTY'] },
  { ticker: 'INDUSINDBK', name: 'IndusInd Bank Ltd.', price: 1495.2, change: -1.8, marketCap: '1.16T', industry: 'Financial Services', indices: ['BANK NIFTY', 'NIFTY 50', 'SENSEX 30', 'FINNIFTY'] },
  { ticker: 'BANKBARODA', name: 'Bank of Baroda', price: 240.5, change: 1.1, marketCap: '1.24T', industry: 'Financial Services', indices: ['BANK NIFTY', 'NIFTY NEXT 50', 'FINNIFTY'] },
  { ticker: 'PNB', name: 'Punjab National Bank', price: 103.2, change: -0.9, marketCap: '1.19T', industry: 'Financial Services', indices: ['BANK NIFTY', 'NIFTY NEXT 50', 'FINNIFTY'] },
  { ticker: 'FEDERALBNK', name: 'Federal Bank Ltd.', price: 158.3, change: 0.8, marketCap: '420B', industry: 'Financial Services', indices: ['BANK NIFTY', 'FINNIFTY'] },
  { ticker: 'IDFCFIRSTB', name: 'IDFC First Bank Ltd.', price: 83, change: 0.5, marketCap: '584B', industry: 'Financial Services', indices: ['BANK NIFTY', 'FINNIFTY'] },
  { ticker: 'AUBANK', name: 'AU Small Finance Bank Ltd.', price: 670, change: -1.2, marketCap: '498B', industry: 'Financial Services', indices: ['BANK NIFTY', 'FINNIFTY'] },
  { ticker: 'BANDHANBNK', name: 'Bandhan Bank Ltd.', price: 185.6, change: -1.2, marketCap: '298B', industry: 'Financial Services', indices: ['BANK NIFTY', 'FINNIFTY'] },
];

export const niftyNext50Stocks = [
  { ticker: 'LICI', name: 'LIC of India', price: 887.75, change: 0.03, marketCap: '5.62T', industry: 'Financial Services', indices: ['NIFTY NEXT 50'] },
  { ticker: 'HAL', name: 'Hindustan Aeronautics Ltd.', price: 4555.10, change: 0.68, marketCap: '3.05T', industry: 'Capital Goods', indices: ['NIFTY NEXT 50'] },
  { ticker: 'DMART', name: 'Avenue Supermarts DMart', price: 4358.20, change: 0.54, marketCap: '2.84T', industry: 'Consumer Services', indices: ['NIFTY NEXT 50'] },
  { ticker: 'INDIGO', name: 'Interglobe Aviation', price: 6002.50, change: 0.55, marketCap: '2.32T', industry: 'Services', indices: ['NIFTY NEXT 50'] },
  { ticker: 'ADANIPOWER', name: 'Adani Power', price: 584.05, change: -0.26, marketCap: '2.25T', industry: 'Power', indices: ['NIFTY NEXT 50'] },
  { ticker: 'IOC', name: 'Indian Oil Corporation', price: 140.13, change: -1.61, marketCap: '1.98T', industry: 'Oil & Gas', indices: ['NIFTY NEXT 50'] },
  { ticker: 'DLF', name: 'DLF', price: 751.55, change: -0.81, marketCap: '1.86T', industry: 'Realty', indices: ['NIFTY NEXT 50'] },
  { ticker: 'HYUNDAI', name: 'Hyundai Motor India', price: 2240.70, change: -0.27, marketCap: '1.82T', industry: 'Automobile', indices: ['NIFTY NEXT 50'] },
  { ticker: 'VBL', name: 'Varun Beverages', price: 501.85, change: -1.81, marketCap: '1.70T', industry: 'Fast Moving Consumer Goods', indices: ['NIFTY NEXT 50'] },
  { ticker: 'VEDL', name: 'Vedanta', price: 430.20, change: -1.95, marketCap: '1.68T', industry: 'Metals & Mining', indices: ['NIFTY NEXT 50'] },
  { ticker: 'PIDILITIND', name: 'Pidilite Industries Ltd.', price: 2983.4, change: 1.2, marketCap: '1.52T', industry: 'Chemicals', indices: ['NIFTY NEXT 50'] },
  { ticker: 'SIEMENS', name: 'Siemens Ltd.', price: 3061.8, change: -2.5, marketCap: '1.09T', industry: 'Capital Goods', indices: ['NIFTY NEXT 50'] },
  { ticker: 'UNITDSPR', name: 'United Spirits Ltd.', price: 1317.2, change: 0.8, marketCap: '958B', industry: 'Fast Moving Consumer Goods', indices: ['NIFTY NEXT 50'] },
  { ticker: 'AMBUJACEM', name: 'Ambuja Cements Ltd.', price: 597.1, change: 1.3, marketCap: '1.47T', industry: 'Construction Materials', indices: ['NIFTY NEXT 50'] },
  { ticker: 'BOSCHLTD', name: 'Bosch Ltd.', price: 38710, change: -1.6, marketCap: '1.14T', industry: 'Automobile and Auto Components', indices: ['NIFTY NEXT 50'] },
  { ticker: 'ICICIGI', name: 'ICICI Lombard General Insurance Company Ltd.', price: 1866.9, change: 0.2, marketCap: '928B', industry: 'Financial Services', indices: ['NIFTY NEXT 50'] },
  { ticker: 'BAJAJHLDNG', name: 'Bajaj Holdings & Investment Ltd.', price: 13797, change: 1.8, marketCap: '1.54T', industry: 'Financial Services', indices: ['NIFTY NEXT 50'] },
  { ticker: 'ADANIENSOL', name: 'Adani Energy Solutions Ltd.', price: 791.3, change: -2.2, marketCap: '950B', industry: 'Power', indices: ['NIFTY NEXT 50'] },
  { ticker: 'TORNTPHARM', name: 'Torrent Pharmaceuticals Ltd.', price: 3548.6, change: 0.4, marketCap: '1.2T', industry: 'Healthcare', indices: ['NIFTY NEXT 50'] },
  { ticker: 'NAUKRI', name: 'Info Edge (India) Ltd.', price: 1333, change: -1.9, marketCap: '863B', industry: 'Consumer Services', indices: ['NIFTY NEXT 50'] },
  { ticker: 'ADANIGREEN', name: 'Adani Green Energy Ltd.', price: 964.1, change: 1.1, marketCap: '1.59T', industry: 'Power', indices: ['NIFTY NEXT 50'] },
  { ticker: 'GAIL', name: 'GAIL (India) Ltd.', price: 170.1, change: -0.3, marketCap: '1.12T', industry: 'Oil, Gas & Consumable Fuels', indices: ['NIFTY NEXT 50'] },
  { ticker: 'CHOLAFIN', name: 'Cholamandalam Investment and Finance Company Ltd.', price: 1447.9, change: 0.9, marketCap: '1.22T', industry: 'Financial Services', indices: ['NIFTY NEXT 50'] },
  { ticker: 'TATAPOWER', name: 'Tata Power Company Ltd.', price: 382.9, change: 2.1, marketCap: '1.22T', industry: 'Power', indices: ['NIFTY NEXT 50'] },
  { ticker: 'SHREECEM', name: 'Shree Cements Ltd.', price: 30230, change: 1.6, marketCap: '1.09T', industry: 'Construction Materials', indices: ['NIFTY NEXT 50'] },
  { ticker: 'MOTHERSON', name: 'Samvardhana Motherson International Ltd.', price: 95.6, change: -2.0, marketCap: '1.01T', industry: 'Automobile and Auto Components', indices: ['NIFTY NEXT 50'] },
  { ticker: 'CANBK', name: 'Canara Bank', price: 106.9, change: -1.3, marketCap: '969B', industry: 'Financial Services', indices: ['NIFTY NEXT 50'] },
  { ticker: 'ABB', name: 'ABB India Ltd.', price: 5033, change: -0.7, marketCap: '1.07T', industry: 'Capital Goods', indices: ['NIFTY NEXT 50'] },
  { ticker: 'JINDALSTEL', name: 'Jindal Steel & Power Ltd.', price: 993.4, change: 2.2, marketCap: '1.01T', industry: 'Metals & Mining', indices: ['NIFTY NEXT 50'] },
  { ticker: 'ZYDUSLIFE', name: 'Zydus Lifesciences Ltd.', price: 935.5, change: -1.1, marketCap: '941B', industry: 'Healthcare', indices: ['NIFTY NEXT 50'] },
  { ticker: 'TVSMOTOR', name: 'TVS Motor Company Ltd.', price: 2960.4, change: 1.4, marketCap: '1.41T', industry: 'Automobile and Auto Components', indices: ['NIFTY NEXT 50'] },
  { ticker: 'PFC', name: 'Power Finance Corporation Ltd.', price: 407.0, change: -0.6, marketCap: '1.34T', industry: 'Financial Services', indices: ['NIFTY NEXT 50'] },
  { ticker: 'IRFC', name: 'Indian Railway Finance Corporation Ltd.', price: 127.5, change: 0.9, marketCap: '1.67T', industry: 'Financial Services', indices: ['NIFTY NEXT 50'] },
  { ticker: 'RECLTD', name: 'REC Ltd.', price: 389.6, change: 1.2, marketCap: '1.03T', industry: 'Financial Services', indices: ['NIFTY NEXT 50'] },
  { ticker: 'LODHA', name: 'Macrotech Developers Ltd.', price: 1215.7, change: -2.3, marketCap: '1.21T', industry: 'Realty', indices: ['NIFTY NEXT 50'] },
  { ticker: 'JSWENERGY', name: 'JSW Energy Ltd.', price: 522.7, change: 0.6, marketCap: '913B', industry: 'Power', indices: ['NIFTY NEXT 50'] },
  { ticker: 'CGPOWER', name: 'CG Power and Industrial Solutions Ltd.', price: 677.3, change: -1.5, marketCap: '1.07T', industry: 'Capital Goods', indices: ['NIFTY NEXT 50'] },
  { ticker: 'DABUR', name: 'Dabur India Ltd.', price: 519.7, change: 0.3, marketCap: '921B', industry: 'Fast Moving Consumer Goods', indices: ['NIFTY NEXT 50'] },
  { ticker: 'GODREJCP', name: 'Godrej Consumer Products Ltd.', price: 1211.6, change: 1.5, marketCap: '1.24T', industry: 'Fast Moving Consumer Goods', indices: ['NIFTY NEXT 50'] },
  { ticker: 'HAVELLS', name: 'Havells India Ltd.', price: 1487.1, change: -0.5, marketCap: '932B', industry: 'Consumer Durables', indices: ['NIFTY NEXT 50'] },
  { ticker: 'ICICIPRULI', name: 'ICICI Prudential Life Insurance Company Ltd.', price: 609.2, change: 2.0, marketCap: '881B', industry: 'Financial Services', indices: ['NIFTY NEXT 50'] },
];

export const bseMidcapStocks = [
  { ticker: 'SOLARINDS', name: 'Solar Industries India Ltd.', price: 15098.00, change: 0.40, marketCap: '1.37T', industry: 'Chemicals', indices: ['BSE MIDCAP'] },
  { ticker: 'TORNTPHARM', name: 'Torrent Pharmaceuticals Ltd.', price: 3611.15, change: -0.19, marketCap: '1.23T', industry: 'Healthcare', indices: ['BSE MIDCAP'] },
  { ticker: 'MAXHEALTH', name: 'Max Healthcare Institute Ltd.', price: 1220.45, change: -3.72, marketCap: '1.19T', industry: 'Healthcare', indices: ['BSE MIDCAP'] },
  { ticker: 'MUTHOOTFIN', name: 'Muthoot Finance Ltd.', price: 2757.55, change: 9.83, marketCap: '1.11T', industry: 'Financial Services', indices: ['BSE MIDCAP'] },
  { ticker: 'INDIANHOTELS', name: 'Indian Hotels Company Ltd.', price: 771.65, change: 0.25, marketCap: '1.10T', industry: 'Hotels & Restaurants', indices: ['BSE MIDCAP'] },
  { ticker: 'MAZDOCK', name: 'Mazagon Dock Shipbuilders Ltd.', price: 2722.05, change: -0.97, marketCap: '1.10T', industry: 'Capital Goods', indices: ['BSE MIDCAP'] },
  { ticker: 'CUMMINSIND', name: 'Cummins India Ltd.', price: 3780.30, change: -0.31, marketCap: '1.05T', industry: 'Capital Goods', indices: ['BSE MIDCAP'] },
  { ticker: 'CGPOWER', name: 'CG Power & Industrial Solutions Ltd.', price: 665.55, change: -0.70, marketCap: '1.02T', industry: 'Capital Goods', indices: ['BSE MIDCAP'] },
  { ticker: 'DIXON', name: 'Dixon Technologies India Ltd.', price: 16725.00, change: 1.58, marketCap: '979B', industry: 'Consumer Durables', indices: ['BSE MIDCAP'] },
  { ticker: 'GMRINFRA', name: 'GMR Airports Infrastructure Ltd.', price: 90.78, change: 2.36, marketCap: '958B', industry: 'Infrastructure', indices: ['BSE MIDCAP'] },
  { ticker: 'INDIANB', name: 'Indian Bank', price: 668.05, change: -0.34, marketCap: '900B', industry: 'Banking', indices: ['BSE MIDCAP'] },
  { ticker: 'LUPIN', name: 'Lupin Ltd.', price: 1962.00, change: -1.37, marketCap: '896B', industry: 'Healthcare', indices: ['BSE MIDCAP'] },
  { ticker: 'BHARTIHEXA', name: 'Bharti Hexacom Ltd.', price: 1700.25, change: 0.19, marketCap: '850B', industry: 'Telecommunications', indices: ['BSE MIDCAP'] },
  { ticker: 'PBFIN', name: 'PB FinTech Ltd.', price: 1832.90, change: -1.11, marketCap: '842B', industry: 'Financial Services', indices: ['BSE MIDCAP'] },
  { ticker: 'HINDPETRO', name: 'Hindustan Petroleum Corporation Ltd.', price: 394.30, change: -4.11, marketCap: '839B', industry: 'Oil & Gas', indices: ['BSE MIDCAP'] },
  { ticker: 'PERSISTENT', name: 'Persistent Systems Ltd.', price: 5293.20, change: 0.87, marketCap: '827B', industry: 'Information Technology', indices: ['BSE MIDCAP'] },
  { ticker: 'NHPC', name: 'NHPC Ltd.', price: 82.25, change: -3.30, marketCap: '827B', industry: 'Power', indices: ['BSE MIDCAP'] },
  { ticker: 'SUZLON', name: 'Suzlon Energy Ltd.', price: 60.06, change: -0.55, marketCap: '823B', industry: 'Power', indices: ['BSE MIDCAP'] },
  { ticker: 'BHEL', name: 'Bharat Heavy Electricals Ltd.', price: 221.70, change: -1.00, marketCap: '771B', industry: 'Capital Goods', indices: ['BSE MIDCAP'] },
  { ticker: 'OFSS', name: 'Oracle Financial Services Software Ltd.', price: 8585.00, change: 0.14, marketCap: '746B', industry: 'Information Technology', indices: ['BSE MIDCAP'] },
  { ticker: 'PAYTM', name: 'One 97 Communications Ltd.', price: 1150.25, change: -0.35, marketCap: '735B', industry: 'Financial Services', indices: ['BSE MIDCAP'] },
  { ticker: 'ASHOKLEY', name: 'Ashok Leyland Ltd.', price: 121.95, change: 1.88, marketCap: '716B', industry: 'Automobile', indices: ['BSE MIDCAP'] },
  { ticker: 'ABSLAMC', name: 'Aditya Birla Capital Ltd.', price: 272.85, change: 1.19, marketCap: '713B', industry: 'Financial Services', indices: ['BSE MIDCAP'] },
  { ticker: 'ABBOTINDIA', name: 'Abbott India Ltd.', price: 33235.85, change: 0.76, marketCap: '707B', industry: 'Healthcare', indices: ['BSE MIDCAP'] },
  { ticker: 'COROMANDEL', name: 'Coromandel International Ltd.', price: 2355.35, change: 4.34, marketCap: '694B', industry: 'Chemicals', indices: ['BSE MIDCAP'] },
  { ticker: 'PRESTIGE', name: 'Prestige Estates Projects Ltd.', price: 1599.00, change: -1.78, marketCap: '690B', industry: 'Realty', indices: ['BSE MIDCAP'] },
  { ticker: 'VISHALMEGA', name: 'Vishal Mega Mart Ltd.', price: 146.50, change: 1.49, marketCap: '683B', industry: 'Consumer Services', indices: ['BSE MIDCAP'] },
  { ticker: 'GICRE', name: 'GIC of India Ltd.', price: 387.20, change: -1.64, marketCap: '678B', industry: 'Financial Services', indices: ['BSE MIDCAP'] },
  { ticker: 'RVNL', name: 'Rail Vikas Nigam Ltd.', price: 324.20, change: -0.63, marketCap: '676B', industry: 'Infrastructure', indices: ['BSE MIDCAP'] },
  { ticker: 'TORNTPOWER', name: 'Torrent Power Ltd.', price: 1329.55, change: -2.48, marketCap: '670B', industry: 'Power', indices: ['BSE MIDCAP'] },
  { ticker: 'UNOMINDA', name: 'UNO Minda Ltd.', price: 1147.90, change: 3.03, marketCap: '660B', industry: 'Automobile', indices: ['BSE MIDCAP'] },
  { ticker: 'OIL', name: 'Oil India Ltd.', price: 400.75, change: -1.54, marketCap: '652B', industry: 'Oil & Gas', indices: ['BSE MIDCAP'] },
  { ticker: 'PATANJALI', name: 'Patanjali Foods Ltd.', price: 1768.25, change: -1.76, marketCap: '640B', industry: 'FMCG', indices: ['BSE MIDCAP'] },
  { ticker: 'ALKEM', name: 'Alkem Laboratories Ltd.', price: 5356.00, change: -0.65, marketCap: '639B', industry: 'Healthcare', indices: ['BSE MIDCAP'] },
  { ticker: 'JSWINFRA', name: 'JSW Infrastructure Ltd.', price: 302.85, change: 1.00, marketCap: '636B', industry: 'Infrastructure', indices: ['BSE MIDCAP'] },
  { ticker: 'AUROPHARMA', name: 'Aurobindo Pharma Ltd.', price: 1082.90, change: 0.53, marketCap: '629B', industry: 'Healthcare', indices: ['BSE MIDCAP'] },
  { ticker: 'NYKAA', name: 'FSN E-Commerce Ventures Ltd.', price: 215.10, change: 0.02, marketCap: '615B', industry: 'Consumer Services', indices: ['BSE MIDCAP'] },
  { ticker: 'NMDC', name: 'NMDC Ltd.', price: 69.44, change: -4.35, marketCap: '610B', industry: 'Metals & Mining', indices: ['BSE MIDCAP'] },
  { ticker: 'SCHAEFFLER', name: 'Schaeffler India Ltd.', price: 3847.10, change: -1.63, marketCap: '603B', industry: 'Automobile', indices: ['BSE MIDCAP'] },
  { ticker: 'JSL', name: 'Jindal Stainless Ltd.', price: 729.75, change: 1.12, marketCap: '601B', industry: 'Metals & Mining', indices: ['BSE MIDCAP'] },
  { ticker: 'TUBEINVEST', name: 'Tube Investments of India Ltd.', price: 3062.20, change: 0.24, marketCap: '593B', industry: 'Automobile', indices: ['BSE MIDCAP'] },
  { ticker: 'YESBANK', name: 'Yes Bank Ltd.', price: 18.78, change: -0.27, marketCap: '589B', industry: 'Banking', indices: ['BSE MIDCAP'] },
  { ticker: 'OBEROIRLTY', name: 'Oberoi Realty Ltd.', price: 1621.50, change: -0.40, marketCap: '589B', industry: 'Realty', indices: ['BSE MIDCAP'] },
  { ticker: 'MRF', name: 'MRF Ltd.', price: 138430.85, change: -0.31, marketCap: '587B', industry: 'Automobile', indices: ['BSE MIDCAP'] },
  { ticker: 'COLPAL', name: 'Colgate-Palmolive (India) Ltd.', price: 2154.15, change: -0.89, marketCap: '586B', industry: 'FMCG', indices: ['BSE MIDCAP'] },
  { ticker: 'GODREJPROP', name: 'Godrej Properties Ltd.', price: 1938.85, change: -1.06, marketCap: '583B', industry: 'Realty', indices: ['BSE MIDCAP'] },
  { ticker: 'IRCTC', name: 'Indian Railway Catering & Tourism Corporation Ltd.', price: 725.10, change: -0.34, marketCap: '580B', industry: 'Transportation', indices: ['BSE MIDCAP'] },
  { ticker: 'GLENMARK', name: 'Glenmark Pharmaceuticals Ltd.', price: 2038.95, change: 0.35, marketCap: '577B', industry: 'Healthcare', indices: ['BSE MIDCAP'] },
  { ticker: 'BHARATFORG', name: 'Bharat Forge Ltd.', price: 1184.30, change: 0.21, marketCap: '564B', industry: 'Automobile', indices: ['BSE MIDCAP'] },
  { ticker: 'PIIND', name: 'PI Industries Ltd.', price: 3671.10, change: -2.67, marketCap: '560B', industry: 'Chemicals', indices: ['BSE MIDCAP'] },
  { ticker: 'AUBANK', name: 'AU Small Finance Bank Ltd.', price: 749.55, change: 1.58, marketCap: '559B', industry: 'Banking', indices: ['BSE MIDCAP'] },
  { ticker: 'MFSL', name: 'Max Financial Services Ltd.', price: 1588.80, change: 0.06, marketCap: '552B', industry: 'Financial Services', indices: ['BSE MIDCAP'] },
  { ticker: 'KALYANKJIL', name: 'Kalyan Jewellers India Ltd.', price: 533.00, change: 3.37, marketCap: '551B', industry: 'Consumer Durables', indices: ['BSE MIDCAP'] },
  { ticker: 'COFORGE', name: 'Coforge Ltd.', price: 1642.00, change: 1.24, marketCap: '549B', industry: 'Information Technology', indices: ['BSE MIDCAP'] },
  { ticker: 'SUPREMEIND', name: 'Supreme Industries Ltd.', price: 4298.00, change: 0.06, marketCap: '546B', industry: 'Plastics', indices: ['BSE MIDCAP'] },
  { ticker: 'LINDEINDIA', name: 'Linde India Ltd.', price: 6223.00, change: 0.00, marketCap: '530B', industry: 'Chemicals', indices: ['BSE MIDCAP'] },
  { ticker: 'MPHASIS', name: 'Mphasis Ltd.', price: 2712.30, change: 0.68, marketCap: '518B', industry: 'Information Technology', indices: ['BSE MIDCAP'] },
  { ticker: 'BANKINDIA', name: 'Bank of India', price: 113.00, change: -0.44, marketCap: '515B', industry: 'Banking', indices: ['BSE MIDCAP'] },
  { ticker: 'UPL', name: 'UPL Ltd.', price: 683.15, change: -0.34, marketCap: '513B', industry: 'Chemicals', indices: ['BSE MIDCAP'] },
  { ticker: 'PHOENIXLTD', name: 'Phoenix Mills Ltd.', price: 1428.95, change: -0.57, marketCap: '511B', industry: 'Realty', indices: ['BSE MIDCAP'] },
  { ticker: 'NAM-INDIA', name: 'Nippon Life India Asset Management Ltd.', price: 802.50, change: 0.48, marketCap: '511B', industry: 'Financial Services', indices: ['BSE MIDCAP'] },
  { ticker: 'UBL', name: 'United Breweries Ltd.', price: 1921.20, change: 0.08, marketCap: '509B', industry: 'FMCG', indices: ['BSE MIDCAP'] },
  { ticker: 'L&TFH', name: 'L&T Finance Holdings Ltd.', price: 202.05, change: 0.42, marketCap: '505B', industry: 'Financial Services', indices: ['BSE MIDCAP'] },
  { ticker: 'IDFCFIRSTB', name: 'IDFC First Bank Ltd.', price: 68.81, change: -1.52, marketCap: '504B', industry: 'Banking', indices: ['BSE MIDCAP'] },
  { ticker: 'SAIL', name: 'Steel Authority of India Ltd.', price: 120.35, change: -2.98, marketCap: '497B', industry: 'Metals & Mining', indices: ['BSE MIDCAP'] },
  { ticker: 'PAGEIND', name: 'Page Industries Ltd.', price: 43600.00, change: 0.17, marketCap: '485B', industry: 'Textiles', indices: ['BSE MIDCAP'] },
  { ticker: 'TATACOMM', name: 'Tata Communications Ltd.', price: 1690.00, change: 3.13, marketCap: '483B', industry: 'Telecommunications', indices: ['BSE MIDCAP'] },
  { ticker: 'FEDERALBNK', name: 'Federal Bank Ltd.', price: 195.95, change: -0.13, marketCap: '481B', industry: 'Banking', indices: ['BSE MIDCAP'] },
  { ticker: 'BIOCON', name: 'Biocon Ltd.', price: 359.10, change: -0.31, marketCap: '480B', industry: 'Healthcare', indices: ['BSE MIDCAP'] },
  { ticker: 'GSKPHARMA', name: 'GlaxoSmithKline Pharmaceuticals Ltd.', price: 2773.85, change: 0.01, marketCap: '469B', industry: 'Healthcare', indices: ['BSE MIDCAP'] },
  { ticker: 'BALKRISIND', name: 'Balkrishna Industries Ltd.', price: 2397.45, change: -0.62, marketCap: '464B', industry: 'Automobile', indices: ['BSE MIDCAP'] },
  { ticker: 'LAURUSLABS', name: 'Laurus Labs Ltd.', price: 859.35, change: -0.47, marketCap: '464B', industry: 'Healthcare', indices: ['BSE MIDCAP'] },
  { ticker: 'APLAPOLLO', name: 'APL Apollo Tubes Ltd.', price: 1607.50, change: 1.62, marketCap: '446B', industry: 'Metals & Mining', indices: ['BSE MIDCAP'] },
  { ticker: 'PREMIER', name: 'Premier Energies Ltd.', price: 985.60, change: -1.34, marketCap: '445B', industry: 'Power', indices: ['BSE MIDCAP'] },
  { ticker: 'LTTS', name: 'L&T Technology Services Ltd.', price: 4153.90, change: 0.37, marketCap: '440B', industry: 'Information Technology', indices: ['BSE MIDCAP'] },
  { ticker: 'PGHH', name: 'Procter & Gamble Hygiene & Health Care Ltd.', price: 13276.90, change: 1.32, marketCap: '431B', industry: 'FMCG', indices: ['BSE MIDCAP'] },
  { ticker: 'DALBHARAT', name: 'Dalmia Bharat Ltd.', price: 2264.60, change: -0.22, marketCap: '426B', industry: 'Cement', indices: ['BSE MIDCAP'] },
  { ticker: 'VOLTAS', name: 'Voltas Ltd.', price: 1271.25, change: -0.40, marketCap: '422B', industry: 'Consumer Durables', indices: ['BSE MIDCAP'] },
  { ticker: 'MAHABANK', name: 'Bank of Maharashtra', price: 54.43, change: -1.25, marketCap: '418B', industry: 'Banking', indices: ['BSE MIDCAP'] },
  { ticker: 'JUBLFOOD', name: 'Jubilant FoodWorks Ltd.', price: 631.65, change: -1.29, marketCap: '417B', industry: 'Consumer Services', indices: ['BSE MIDCAP'] },
  { ticker: 'PETRONET', name: 'Petronet LNG Ltd.', price: 271.90, change: -1.07, marketCap: '408B', industry: 'Oil & Gas', indices: ['BSE MIDCAP'] },
  { ticker: 'CONCOR', name: 'Container Corporation of India Ltd.', price: 532.05, change: -1.78, marketCap: '405B', industry: 'Transportation', indices: ['BSE MIDCAP'] },
  { ticker: 'IREDA', name: 'Indian Renewable Energy Development Agency Ltd.', price: 143.85, change: -0.24, marketCap: '404B', industry: 'Financial Services', indices: ['BSE MIDCAP'] },
  { ticker: 'GODREJIND', name: 'Godrej Industries Ltd.', price: 1182.45, change: 0.61, marketCap: '398B', industry: 'Chemicals', indices: ['BSE MIDCAP'] },
  { ticker: 'CRISIL', name: 'CRISIL Ltd.', price: 5300.00, change: 1.88, marketCap: '390B', industry: 'Financial Services', indices: ['BSE MIDCAP'] },
  { ticker: 'THERMAX', name: 'Thermax Ltd.', price: 3281.00, change: -0.34, marketCap: '390B', industry: 'Capital Goods', indices: ['BSE MIDCAP'] },
  { ticker: 'ESCORTS', name: 'Escorts Kubota Ltd.', price: 3394.55, change: 0.64, marketCap: '380B', industry: 'Automobile', indices: ['BSE MIDCAP'] },
  { ticker: 'GUJFLUORO', name: 'Gujarat Fluorochemicals Ltd.', price: 3378.00, change: -0.53, marketCap: '372B', industry: 'Chemicals', indices: ['BSE MIDCAP'] },
  { ticker: 'ENDURANCE', name: 'Endurance Technologies Ltd.', price: 2613.00, change: 3.24, marketCap: '366B', industry: 'Automobile', indices: ['BSE MIDCAP'] },
  { ticker: 'SJVN', name: 'SJVN Ltd.', price: 92.02, change: -1.53, marketCap: '361B', industry: 'Power', indices: ['BSE MIDCAP'] },
  { ticker: 'M&MFIN', name: 'Mahindra & Mahindra Financial Services Ltd.', price: 255.00, change: -1.47, marketCap: '355B', industry: 'Financial Services', indices: ['BSE MIDCAP'] },
  { ticker: 'TATAELXSI', name: 'Tata Elxsi Ltd.', price: 5678.80, change: 0.08, marketCap: '354B', industry: 'Information Technology', indices: ['BSE MIDCAP'] },
  { ticker: 'UCOBANK', name: 'UCO Bank', price: 28.08, change: 0.11, marketCap: '352B', industry: 'Banking', indices: ['BSE MIDCAP'] },
  { ticker: 'IPCA', name: 'IPCA Laboratories Ltd.', price: 1367.85, change: 0.27, marketCap: '347B', industry: 'Healthcare', indices: ['BSE MIDCAP'] },
  { ticker: 'DELHIVERY', name: 'Delhivery Ltd.', price: 463.70, change: -0.74, marketCap: '346B', industry: 'Transportation', indices: ['BSE MIDCAP'] },
  { ticker: 'ASTRAL', name: 'Astral Ltd.', price: 1278.90, change: -1.06, marketCap: '344B', industry: 'Chemicals', indices: ['BSE MIDCAP'] },
  { ticker: '3MINDIA', name: '3M India Ltd.', price: 30294.90, change: -0.60, marketCap: '342B', industry: 'Consumer Durables', indices: ['BSE MIDCAP'] },
  { ticker: 'ACC', name: 'ACC Ltd.', price: 1782.90, change: -0.32, marketCap: '335B', industry: 'Cement', indices: ['BSE MIDCAP'] },
  { ticker: 'GILLETTE', name: 'Gillette India Ltd.', price: 10290.25, change: -1.93, marketCap: '334B', industry: 'FMCG', indices: ['BSE MIDCAP'] },
  { ticker: 'KPITTECH', name: 'KPIT Technologies Ltd.', price: 1209.30, change: -0.53, marketCap: '333B', industry: 'Information Technology', indices: ['BSE MIDCAP'] },
  { ticker: 'GODIGIT', name: 'Go Digit General Insurance Ltd.', price: 352.85, change: -1.33, marketCap: '328B', industry: 'Financial Services', indices: ['BSE MIDCAP'] },
  { ticker: 'HONAUT', name: 'Honeywell Automation India Ltd.', price: 36900.00, change: 0.16, marketCap: '328B', industry: 'Capital Goods', indices: ['BSE MIDCAP'] },
  { ticker: 'CENTRALBK', name: 'Central Bank of India', price: 36.15, change: 0.39, marketCap: '327B', industry: 'Banking', indices: ['BSE MIDCAP'] },
  { ticker: 'GLAND', name: 'Gland Pharma Ltd.', price: 1967.55, change: 0.88, marketCap: '326B', industry: 'Healthcare', indices: ['BSE MIDCAP'] },
  { ticker: 'AWL', name: 'AWL Agri Business Ltd.', price: 249.80, change: -1.07, marketCap: '325B', industry: 'Agro Chemicals', indices: ['BSE MIDCAP'] },
  { ticker: 'EXIDEIND', name: 'Exide Industries Ltd.', price: 374.30, change: -0.33, marketCap: '318B', industry: 'Automobile', indices: ['BSE MIDCAP'] },
  { ticker: 'LICHSGFIN', name: 'LIC Housing Finance Ltd.', price: 568.20, change: -1.06, marketCap: '313B', industry: 'Financial Services', indices: ['BSE MIDCAP'] },
  { ticker: 'NIACL', name: 'The New India Assurance Company Ltd.', price: 185.90, change: -0.03, marketCap: '304B', industry: 'Financial Services', indices: ['BSE MIDCAP'] },
  { ticker: 'AIAENG', name: 'AIA Engineering Ltd.', price: 3113.85, change: -0.15, marketCap: '291B', industry: 'Capital Goods', indices: ['BSE MIDCAP'] },
  { ticker: 'GUJGAS', name: 'Gujarat Gas Ltd.', price: 422.50, change: -0.65, marketCap: '291B', industry: 'Oil & Gas', indices: ['BSE MIDCAP'] },
  { ticker: 'IGL', name: 'Indraprastha Gas Ltd.', price: 203.50, change: -1.31, marketCap: '286B', industry: 'Oil & Gas', indices: ['BSE MIDCAP'] },
  { ticker: 'SONACOMS', name: 'Sona BLW Precision Forgings Ltd.', price: 452.50, change: 0.86, marketCap: '281B', industry: 'Automobile', indices: ['BSE MIDCAP'] },
  { ticker: 'EMCURE', name: 'Emcure Pharmaceuticals Ltd.', price: 1454.60, change: 0.07, marketCap: '276B', industry: 'Healthcare', indices: ['BSE MIDCAP'] },
  { ticker: 'TATATECH', name: 'Tata Technologies Ltd.', price: 663.70, change: -0.40, marketCap: '269B', industry: 'Information Technology', indices: ['BSE MIDCAP'] },
  { ticker: 'INVENTURUS', name: 'Inventurus Knowledge Solutions Ltd.', price: 1556.80, change: 0.03, marketCap: '267B', industry: 'Information Technology', indices: ['BSE MIDCAP'] },
  { ticker: 'BANDHANBNK', name: 'Bandhan Bank Ltd.', price: 163.10, change: -1.48, marketCap: '263B', industry: 'Banking', indices: ['BSE MIDCAP'] },
  { ticker: 'STARHEALTH', name: 'Star Health and Allied Insurance Company Ltd.', price: 436.85, change: -1.69, marketCap: '258B', industry: 'Financial Services', indices: ['BSE MIDCAP'] },
  { ticker: 'PEL', name: 'Piramal Enterprises Ltd.', price: 1121.10, change: -0.65, marketCap: '254B', industry: 'Financial Services', indices: ['BSE MIDCAP'] },
  { ticker: 'EMAMILTD', name: 'Emami Ltd.', price: 580.00, change: -0.42, marketCap: '254B', industry: 'FMCG', indices: ['BSE MIDCAP'] },
  { ticker: 'BAYERCROP', name: 'Bayer CropScience Ltd.', price: 5655.70, change: 0.04, marketCap: '254B', industry: 'Agro Chemicals', indices: ['BSE MIDCAP'] },
  { ticker: 'DEEPAKNTR', name: 'Deepak Nitrite Ltd.', price: 1831.50, change: -2.19, marketCap: '253B', industry: 'Chemicals', indices: ['BSE MIDCAP'] },
  { ticker: 'RAMCOCEM', name: 'The Ramco Cements Ltd.', price: 1065.30, change: -0.12, marketCap: '252B', industry: 'Cement', indices: ['BSE MIDCAP'] },
  { ticker: 'SUNTV', name: 'Sun TV Network Ltd.', price: 573.45, change: -2.12, marketCap: '227B', industry: 'Media & Entertainment', indices: ['BSE MIDCAP'] },
  { ticker: 'CROMPTON', name: 'Crompton Greaves Consumer Electricals Ltd.', price: 319.90, change: 0.41, marketCap: '206B', industry: 'Consumer Durables', indices: ['BSE MIDCAP'] },
  { ticker: 'CASTROLIND', name: 'Castrol India Ltd.', price: 205.85, change: -1.08, marketCap: '203B', industry: 'Oil & Gas', indices: ['BSE MIDCAP'] },
  { ticker: 'PSB', name: 'Punjab & Sind Bank', price: 28.14, change: -0.18, marketCap: '199B', industry: 'Banking', indices: ['BSE MIDCAP'] },
  { ticker: 'FIRSTCRY', name: 'Firstcry (Brainbees Solutions) Ltd.', price: 369.85, change: -1.31, marketCap: '193B', industry: 'Consumer Services', indices: ['BSE MIDCAP'] },
  { ticker: 'KANSAINER', name: 'Kansai Nerolac Paints Ltd.', price: 236.10, change: -0.08, marketCap: '190B', industry: 'Chemicals', indices: ['BSE MIDCAP'] },
  { ticker: 'OLA', name: 'Ola Electric Mobility Ltd.', price: 41.32, change: 2.00, marketCap: '182B', industry: 'Automobile', indices: ['BSE MIDCAP'] },
  { ticker: 'VEDANT', name: 'Vedant Fashions Ltd.', price: 743.80, change: 0.67, marketCap: '181B', industry: 'Textiles', indices: ['BSE MIDCAP'] },
  { ticker: 'WHIRLPOOL', name: 'Whirlpool of India Ltd.', price: 1239.30, change: -0.20, marketCap: '157B', industry: 'Consumer Durables', indices: ['BSE MIDCAP'] },
  { ticker: 'AARTIIND', name: 'Aarti Industries Ltd.', price: 375.90, change: -1.82, marketCap: '136B', industry: 'Chemicals', indices: ['BSE MIDCAP'] },
  { ticker: 'CLEAN', name: 'Clean Science and Technology Ltd.', price: 1187.30, change: -3.46, marketCap: '125B', industry: 'Chemicals', indices: ['BSE MIDCAP'] },
  { ticker: 'ZEEL', name: 'Zee Entertainment Enterprises Ltd.', price: 116.20, change: -0.47, marketCap: '112B', industry: 'Media & Entertainment', indices: ['BSE MIDCAP'] },
  { ticker: 'RELAXO', name: 'Relaxo Footwears Ltd.', price: 437.65, change: 1.09, marketCap: '109B', industry: 'Consumer Durables', indices: ['BSE MIDCAP'] },
  { ticker: 'ABFRL', name: 'Aditya Birla Fashion and Retail Ltd.', price: 75.01, change: 0.41, marketCap: '92B', industry: 'Textiles', indices: ['BSE MIDCAP'] },
  { ticker: 'AJANTPHARM', name: 'Ajanta Pharma Ltd.', price: 2678.80, change: 0.40, marketCap: '32B', industry: 'Healthcare', indices: ['BSE MIDCAP'] },
];

export const bseSmallCapStocks = [
  { ticker: 'SOLARINDS', name: 'Solar Industries India Ltd.', price: 15098.00, change: 0.40, marketCap: '1.37T', industry: 'Chemicals', indices: ['BSE SMALLCAP'] },
  { ticker: 'TORNTPHARM', name: 'Torrent Pharmaceuticals Ltd.', price: 3611.15, change: -0.19, marketCap: '1.23T', industry: 'Healthcare', indices: ['BSE SMALLCAP'] },
  { ticker: 'MAXHEALTH', name: 'Max Healthcare Institute Ltd.', price: 1220.45, change: -3.72, marketCap: '1.19T', industry: 'Healthcare', indices: ['BSE SMALLCAP'] },
  { ticker: 'MUTHOOTFIN', name: 'Muthoot Finance Ltd.', price: 2757.55, change: 9.83, marketCap: '1.11T', industry: 'Financial Services', indices: ['BSE SMALLCAP'] },
  { ticker: 'INDIANHOTELS', name: 'Indian Hotels Company Ltd.', price: 771.65, change: 0.25, marketCap: '1.10T', industry: 'Hotels & Restaurants', indices: ['BSE SMALLCAP'] },
  { ticker: 'MAZDOCK', name: 'Mazagon Dock Shipbuilders Ltd.', price: 2722.05, change: -0.97, marketCap: '1.10T', industry: 'Capital Goods', indices: ['BSE SMALLCAP'] },
  { ticker: 'CUMMINSIND', name: 'Cummins India Ltd.', price: 3780.30, change: -0.31, marketCap: '1.05T', industry: 'Capital Goods', indices: ['BSE SMALLCAP'] },
  { ticker: 'CGPOWER', name: 'CG Power & Industrial Solutions Ltd.', price: 665.55, change: -0.70, marketCap: '1.02T', industry: 'Capital Goods', indices: ['BSE SMALLCAP'] },
  { ticker: 'DIXON', name: 'Dixon Technologies India Ltd.', price: 16200.00, change: 1.58, marketCap: '979B', industry: 'Consumer Durables', indices: ['BSE SMALLCAP'] },
  { ticker: 'GMRINFRA', name: 'GMR Airports Infrastructure Ltd.', price: 90.78, change: 2.36, marketCap: '958B', industry: 'Infrastructure', indices: ['BSE SMALLCAP'] },
  { ticker: 'INDIANB', name: 'Indian Bank', price: 668.05, change: -0.34, marketCap: '900B', industry: 'Banking', indices: ['BSE SMALLCAP'] },
  { ticker: 'LUPIN', name: 'Lupin Ltd.', price: 1962.00, change: -1.37, marketCap: '896B', industry: 'Healthcare', indices: ['BSE SMALLCAP'] },
  { ticker: 'BHARTIHEXA', name: 'Bharti Hexacom Ltd.', price: 1700.25, change: 0.19, marketCap: '850B', industry: 'Telecommunications', indices: ['BSE SMALLCAP'] },
  { ticker: 'PBFIN', name: 'PB FinTech Ltd.', price: 1832.90, change: -1.11, marketCap: '842B', industry: 'Financial Services', indices: ['BSE SMALLCAP'] },
  { ticker: 'HINDPETRO', name: 'Hindustan Petroleum Corporation Ltd.', price: 394.30, change: -4.11, marketCap: '839B', industry: 'Oil & Gas', indices: ['BSE SMALLCAP'] },
  { ticker: 'PERSISTENT', name: 'Persistent Systems Ltd.', price: 5293.20, change: 0.87, marketCap: '827B', industry: 'Information Technology', indices: ['BSE SMALLCAP'] },
  { ticker: 'NHPC', name: 'NHPC Ltd.', price: 82.25, change: -3.30, marketCap: '827B', industry: 'Power', indices: ['BSE SMALLCAP'] },
  { ticker: 'SUZLON', name: 'Suzlon Energy Ltd.', price: 60.06, change: -0.55, marketCap: '823B', industry: 'Power', indices: ['BSE SMALLCAP'] },
  { ticker: 'BHEL', name: 'Bharat Heavy Electricals Ltd.', price: 221.70, change: -1.00, marketCap: '771B', industry: 'Capital Goods', indices: ['BSE SMALLCAP'] },
  { ticker: 'OFSS', name: 'Oracle Financial Services Software Ltd.', price: 8585.00, change: 0.14, marketCap: '746B', industry: 'Information Technology', indices: ['BSE SMALLCAP'] },
  { ticker: 'PAYTM', name: 'One 97 Communications Ltd.', price: 1150.25, change: -0.35, marketCap: '735B', industry: 'Financial Services', indices: ['BSE SMALLCAP'] },
  { ticker: 'ASHOKLEY', name: 'Ashok Leyland Ltd.', price: 121.95, change: 1.88, marketCap: '716B', industry: 'Automobile', indices: ['BSE SMALLCAP'] },
  { ticker: 'ABSLAMC', name: 'Aditya Birla Capital Ltd.', price: 272.85, change: 1.19, marketCap: '713B', industry: 'Financial Services', indices: ['BSE SMALLCAP'] },
  { ticker: 'ABBOTINDIA', name: 'Abbott India Ltd.', price: 33235.85, change: 0.76, marketCap: '707B', industry: 'Healthcare', indices: ['BSE SMALLCAP'] },
  { ticker: 'COROMANDEL', name: 'Coromandel International Ltd.', price: 2355.35, change: 4.34, marketCap: '694B', industry: 'Chemicals', indices: ['BSE SMALLCAP'] },
  { ticker: 'PRESTIGE', name: 'Prestige Estates Projects Ltd.', price: 1599.00, change: -1.78, marketCap: '690B', industry: 'Realty', indices: ['BSE SMALLCAP'] },
  { ticker: 'VISHALMEGA', name: 'Vishal Mega Mart Ltd.', price: 146.50, change: 1.49, marketCap: '683B', industry: 'Consumer Services', indices: ['BSE SMALLCAP'] },
  { ticker: 'GICRE', name: 'GIC of India Ltd.', price: 387.20, change: -1.64, marketCap: '678B', industry: 'Financial Services', indices: ['BSE SMALLCAP'] },
  { ticker: 'RVNL', name: 'Rail Vikas Nigam Ltd.', price: 324.20, change: -0.63, marketCap: '676B', industry: 'Infrastructure', indices: ['BSE SMALLCAP'] },
  { ticker: 'TORNTPOWER', name: 'Torrent Power Ltd.', price: 1329.55, change: -2.48, marketCap: '670B', industry: 'Power', indices: ['BSE SMALLCAP'] },
  { ticker: 'UNOMINDA', name: 'UNO Minda Ltd.', price: 1147.90, change: 3.03, marketCap: '660B', industry: 'Automobile', indices: ['BSE SMALLCAP'] },
  { ticker: 'OIL', name: 'Oil India Ltd.', price: 400.75, change: -1.54, marketCap: '652B', industry: 'Oil & Gas', indices: ['BSE SMALLCAP'] },
  { ticker: 'PATANJALI', name: 'Patanjali Foods Ltd.', price: 1768.25, change: -1.76, marketCap: '640B', industry: 'FMCG', indices: ['BSE SMALLCAP'] },
  { ticker: 'ALKEM', name: 'Alkem Laboratories Ltd.', price: 5356.00, change: -0.65, marketCap: '639B', industry: 'Healthcare', indices: ['BSE SMALLCAP'] },
  { ticker: 'JSWINFRA', name: 'JSW Infrastructure Ltd.', price: 302.85, change: 1.00, marketCap: '636B', industry: 'Infrastructure', indices: ['BSE SMALLCAP'] },
  { ticker: 'AUROPHARMA', name: 'Aurobindo Pharma Ltd.', price: 1082.90, change: 0.53, marketCap: '629B', industry: 'Healthcare', indices: ['BSE SMALLCAP'] },
  { ticker: 'NYKAA', name: 'FSN E-Commerce Ventures Ltd.', price: 215.10, change: 0.02, marketCap: '615B', industry: 'Consumer Services', indices: ['BSE SMALLCAP'] },
  { ticker: 'NMDC', name: 'NMDC Ltd.', price: 69.44, change: -4.35, marketCap: '610B', industry: 'Metals & Mining', indices: ['BSE SMALLCAP'] },
  { ticker: 'SCHAEFFLER', name: 'Schaeffler India Ltd.', price: 3847.10, change: -1.63, marketCap: '603B', industry: 'Automobile', indices: ['BSE SMALLCAP'] },
  { ticker: 'JSL', name: 'Jindal Stainless Ltd.', price: 729.75, change: 1.12, marketCap: '601B', industry: 'Metals & Mining', indices: ['BSE SMALLCAP'] },
  { ticker: 'TUBEINVEST', name: 'Tube Investments of India Ltd.', price: 3062.20, change: 0.24, marketCap: '593B', industry: 'Automobile', indices: ['BSE SMALLCAP'] },
  { ticker: 'YESBANK', name: 'Yes Bank Ltd.', price: 18.78, change: -0.27, marketCap: '589B', industry: 'Banking', indices: ['BSE SMALLCAP'] },
  { ticker: 'OBEROIRLTY', name: 'Oberoi Realty Ltd.', price: 1621.50, change: -0.40, marketCap: '589B', industry: 'Realty', indices: ['BSE SMALLCAP'] },
  { ticker: 'MRF', name: 'MRF Ltd.', price: 138430.85, change: -0.31, marketCap: '587B', industry: 'Automobile', indices: ['BSE SMALLCAP'] },
  { ticker: 'COLPAL', name: 'Colgate-Palmolive (India) Ltd.', price: 2154.15, change: -0.89, marketCap: '586B', industry: 'FMCG', indices: ['BSE SMALLCAP'] },
  { ticker: 'GODREJPROP', name: 'Godrej Properties Ltd.', price: 1938.85, change: -1.06, marketCap: '583B', industry: 'Realty', indices: ['BSE SMALLCAP'] },
  { ticker: 'IRCTC', name: 'Indian Railway Catering & Tourism Corporation Ltd.', price: 725.10, change: -0.34, marketCap: '580B', industry: 'Transportation', indices: ['BSE SMALLCAP'] },
  { ticker: 'GLENMARK', name: 'Glenmark Pharmaceuticals Ltd.', price: 2038.95, change: 0.35, marketCap: '577B', industry: 'Healthcare', indices: ['BSE SMALLCAP'] },
  { ticker: 'BHARATFORG', name: 'Bharat Forge Ltd.', price: 1184.30, change: 0.21, marketCap: '564B', industry: 'Automobile', indices: ['BSE SMALLCAP'] },
  { ticker: 'PIIND', name: 'PI Industries Ltd.', price: 3671.10, change: -2.67, marketCap: '560B', industry: 'Chemicals', indices: ['BSE SMALLCAP'] },
  { ticker: 'AUBANK', name: 'AU Small Finance Bank Ltd.', price: 749.55, change: 1.58, marketCap: '559B', industry: 'Banking', indices: ['BSE SMALLCAP'] },
  { ticker: 'MFSL', name: 'Max Financial Services Ltd.', price: 1588.80, change: 0.06, marketCap: '552B', industry: 'Financial Services', indices: ['BSE SMALLCAP'] },
  { ticker: 'KALYANKJIL', name: 'Kalyan Jewellers India Ltd.', price: 533.00, change: 3.37, marketCap: '551B', industry: 'Consumer Durables', indices: ['BSE SMALLCAP'] },
  { ticker: 'COFORGE', name: 'Coforge Ltd.', price: 1642.00, change: 1.24, marketCap: '549B', industry: 'Information Technology', indices: ['BSE SMALLCAP'] },
  { ticker: 'SUPREMEIND', name: 'Supreme Industries Ltd.', price: 4298.00, change: 0.06, marketCap: '546B', industry: 'Plastics', indices: ['BSE SMALLCAP'] },
  { ticker: 'LINDEINDIA', name: 'Linde India Ltd.', price: 6223.00, change: 0.00, marketCap: '530B', industry: 'Chemicals', indices: ['BSE SMALLCAP'] },
  { ticker: 'MPHASIS', name: 'Mphasis Ltd.', price: 2712.30, change: 0.68, marketCap: '518B', industry: 'Information Technology', indices: ['BSE SMALLCAP'] },
  { ticker: 'BANKINDIA', name: 'Bank of India', price: 113.00, change: -0.44, marketCap: '515B', industry: 'Banking', indices: ['BSE SMALLCAP'] },
  { ticker: 'UPL', name: 'UPL Ltd.', price: 683.15, change: -0.34, marketCap: '513B', industry: 'Chemicals', indices: ['BSE SMALLCAP'] },
  { ticker: 'PHOENIXLTD', name: 'Phoenix Mills Ltd.', price: 1428.95, change: -0.57, marketCap: '511B', industry: 'Realty', indices: ['BSE SMALLCAP'] },
  { ticker: 'NAM-INDIA', name: 'Nippon Life India Asset Management Ltd.', price: 802.50, change: 0.48, marketCap: '511B', industry: 'Financial Services', indices: ['BSE SMALLCAP'] },
  { ticker: 'UBL', name: 'United Breweries Ltd.', price: 1921.20, change: 0.08, marketCap: '509B', industry: 'FMCG', indices: ['BSE SMALLCAP'] },
  { ticker: 'L&TFH', name: 'L&T Finance Holdings Ltd.', price: 202.05, change: 0.42, marketCap: '505B', industry: 'Financial Services', indices: ['BSE SMALLCAP'] },
  { ticker: 'IDFCFIRSTB', name: 'IDFC First Bank Ltd.', price: 68.81, change: -1.52, marketCap: '504B', industry: 'Banking', indices: ['BSE SMALLCAP'] },
  { ticker: 'SAIL', name: 'Steel Authority of India Ltd.', price: 120.35, change: -2.98, marketCap: '497B', industry: 'Metals & Mining', indices: ['BSE SMALLCAP'] },
  { ticker: 'PAGEIND', name: 'Page Industries Ltd.', price: 43600.00, change: 0.17, marketCap: '485B', industry: 'Textiles', indices: ['BSE SMALLCAP'] },
  { ticker: 'TATACOMM', name: 'Tata Communications Ltd.', price: 1690.00, change: 3.13, marketCap: '483B', industry: 'Telecommunications', indices: ['BSE SMALLCAP'] },
  { ticker: 'FEDERALBNK', name: 'Federal Bank Ltd.', price: 195.95, change: -0.13, marketCap: '481B', industry: 'Banking', indices: ['BSE SMALLCAP'] },
  { ticker: 'BIOCON', name: 'Biocon Ltd.', price: 359.10, change: -0.31, marketCap: '480B', industry: 'Healthcare', indices: ['BSE SMALLCAP'] },
  { ticker: 'GSKPHARMA', name: 'GlaxoSmithKline Pharmaceuticals Ltd.', price: 2773.85, change: 0.01, marketCap: '469B', industry: 'Healthcare', indices: ['BSE SMALLCAP'] },
  { ticker: 'BALKRISIND', name: 'Balkrishna Industries Ltd.', price: 2397.45, change: -0.62, marketCap: '464B', industry: 'Automobile', indices: ['BSE SMALLCAP'] },
  { ticker: 'LAURUSLABS', name: 'Laurus Labs Ltd.', price: 859.35, change: -0.47, marketCap: '464B', industry: 'Healthcare', indices: ['BSE SMALLCAP'] },
  { ticker: 'APLAPOLLO', name: 'APL Apollo Tubes Ltd.', price: 1607.50, change: 1.62, marketCap: '446B', industry: 'Metals & Mining', indices: ['BSE SMALLCAP'] },
  { ticker: 'PREMIER', name: 'Premier Energies Ltd.', price: 985.60, change: -1.34, marketCap: '445B', industry: 'Power', indices: ['BSE SMALLCAP'] },
  { ticker: 'LTTS', name: 'L&T Technology Services Ltd.', price: 4153.90, change: 0.37, marketCap: '440B', industry: 'Information Technology', indices: ['BSE SMALLCAP'] },
  { ticker: 'PGHH', name: 'Procter & Gamble Hygiene & Health Care Ltd.', price: 13276.90, change: 1.32, marketCap: '431B', industry: 'FMCG', indices: ['BSE SMALLCAP'] },
  { ticker: 'DALBHARAT', name: 'Dalmia Bharat Ltd.', price: 2264.60, change: -0.22, marketCap: '426B', industry: 'Cement', indices: ['BSE SMALLCAP'] },
  { ticker: 'VOLTAS', name: 'Voltas Ltd.', price: 1271.25, change: -0.40, marketCap: '422B', industry: 'Consumer Durables', indices: ['BSE SMALLCAP'] },
  { ticker: 'MAHABANK', name: 'Bank of Maharashtra', price: 54.43, change: -1.25, marketCap: '418B', industry: 'Banking', indices: ['BSE SMALLCAP'] },
  { ticker: 'JUBLFOOD', name: 'Jubilant FoodWorks Ltd.', price: 631.65, change: -1.29, marketCap: '417B', industry: 'Consumer Services', indices: ['BSE SMALLCAP'] },
  { ticker: 'PETRONET', name: 'Petronet LNG Ltd.', price: 271.90, change: -1.07, marketCap: '408B', industry: 'Oil & Gas', indices: ['BSE SMALLCAP'] },
  { ticker: 'CONCOR', name: 'Container Corporation of India Ltd.', price: 532.05, change: -1.78, marketCap: '405B', industry: 'Transportation', indices: ['BSE SMALLCAP'] },
  { ticker: 'IREDA', name: 'Indian Renewable Energy Development Agency Ltd.', price: 143.85, change: -0.24, marketCap: '404B', industry: 'Financial Services', indices: ['BSE SMALLCAP'] },
  { ticker: 'GODREJIND', name: 'Godrej Industries Ltd.', price: 1182.45, change: 0.61, marketCap: '398B', industry: 'Chemicals', indices: ['BSE SMALLCAP'] },
  { ticker: 'CRISIL', name: 'CRISIL Ltd.', price: 5300.00, change: 1.88, marketCap: '390B', industry: 'Financial Services', indices: ['BSE SMALLCAP'] },
  { ticker: 'THERMAX', name: 'Thermax Ltd.', price: 3281.00, change: -0.34, marketCap: '390B', industry: 'Capital Goods', indices: ['BSE SMALLCAP'] },
  { ticker: 'ESCORTS', name: 'Escorts Kubota Ltd.', price: 3394.55, change: 0.64, marketCap: '380B', industry: 'Automobile', indices: ['BSE SMALLCAP'] },
  { ticker: 'GUJFLUORO', name: 'Gujarat Fluorochemicals Ltd.', price: 3378.00, change: -0.53, marketCap: '372B', industry: 'Chemicals', indices: ['BSE SMALLCAP'] },
  { ticker: 'ENDURANCE', name: 'Endurance Technologies Ltd.', price: 2613.00, change: 3.24, marketCap: '366B', industry: 'Automobile', indices: ['BSE SMALLCAP'] },
  { ticker: 'SJVN', name: 'SJVN Ltd.', price: 92.02, change: -1.53, marketCap: '361B', industry: 'Power', indices: ['BSE SMALLCAP'] },
  { ticker: 'M&MFIN', name: 'Mahindra & Mahindra Financial Services Ltd.', price: 255.00, change: -1.47, marketCap: '355B', industry: 'Financial Services', indices: ['BSE SMALLCAP'] },
  { ticker: 'TATAELXSI', name: 'Tata Elxsi Ltd.', price: 5678.80, change: 0.08, marketCap: '354B', industry: 'Information Technology', indices: ['BSE SMALLCAP'] },
  { ticker: 'UCOBANK', name: 'UCO Bank', price: 28.08, change: 0.11, marketCap: '352B', industry: 'Banking', indices: ['BSE SMALLCAP'] },
  { ticker: 'IPCA', name: 'IPCA Laboratories Ltd.', price: 1367.85, change: 0.27, marketCap: '347B', industry: 'Healthcare', indices: ['BSE SMALLCAP'] },
  { ticker: 'DELHIVERY', name: 'Delhivery Ltd.', price: 463.70, change: -0.74, marketCap: '346B', industry: 'Transportation', indices: ['BSE SMALLCAP'] },
  { ticker: 'ASTRAL', name: 'Astral Ltd.', price: 1278.90, change: -1.06, marketCap: '344B', industry: 'Chemicals', indices: ['BSE SMALLCAP'] },
  { ticker: '3MINDIA', name: '3M India Ltd.', price: 30294.90, change: -0.60, marketCap: '342B', industry: 'Consumer Durables', indices: ['BSE SMALLCAP'] },
  { ticker: 'ACC', name: 'ACC Ltd.', price: 1782.90, change: -0.32, marketCap: '335B', industry: 'Cement', indices: ['BSE SMALLCAP'] },
  { ticker: 'GILLETTE', name: 'Gillette India Ltd.', price: 10290.25, change: -1.93, marketCap: '334B', industry: 'FMCG', indices: ['BSE SMALLCAP'] },
  { ticker: 'KPITTECH', name: 'KPIT Technologies Ltd.', price: 1209.30, change: -0.53, marketCap: '333B', industry: 'Information Technology', indices: ['BSE SMALLCAP'] },
  { ticker: 'GODIGIT', name: 'Go Digit General Insurance Ltd.', price: 352.85, change: -1.33, marketCap: '328B', industry: 'Financial Services', indices: ['BSE SMALLCAP'] },
  { ticker: 'HONAUT', name: 'Honeywell Automation India Ltd.', price: 36900.00, change: 0.16, marketCap: '328B', industry: 'Capital Goods', indices: ['BSE SMALLCAP'] },
  { ticker: 'CENTRALBK', name: 'Central Bank of India', price: 36.15, change: 0.39, marketCap: '327B', industry: 'Banking', indices: ['BSE SMALLCAP'] },
  { ticker: 'GLAND', name: 'Gland Pharma Ltd.', price: 1967.55, change: 0.88, marketCap: '326B', industry: 'Healthcare', indices: ['BSE SMALLCAP'] },
  { ticker: 'AWL', name: 'AWL Agri Business Ltd.', price: 249.80, change: -1.07, marketCap: '325B', industry: 'Agro Chemicals', indices: ['BSE SMALLCAP'] },
  { ticker: 'EXIDEIND', name: 'Exide Industries Ltd.', price: 374.30, change: -0.33, marketCap: '318B', industry: 'Automobile', indices: ['BSE SMALLCAP'] },
  { ticker: 'LICHSGFIN', name: 'LIC Housing Finance Ltd.', price: 568.20, change: -1.06, marketCap: '313B', industry: 'Financial Services', indices: ['BSE SMALLCAP'] },
  { ticker: 'NIACL', name: 'The New India Assurance Company Ltd.', price: 185.90, change: -0.03, marketCap: '304B', industry: 'Financial Services', indices: ['BSE SMALLCAP'] },
  { ticker: 'AIAENG', name: 'AIA Engineering Ltd.', price: 3113.85, change: -0.15, marketCap: '291B', industry: 'Capital Goods', indices: ['BSE SMALLCAP'] },
  { ticker: 'GUJGAS', name: 'Gujarat Gas Ltd.', price: 422.50, change: -0.65, marketCap: '291B', industry: 'Oil & Gas', indices: ['BSE SMALLCAP'] },
  { ticker: 'IGL', name: 'Indraprastha Gas Ltd.', price: 203.50, change: -1.31, marketCap: '286B', industry: 'Oil & Gas', indices: ['BSE SMALLCAP'] },
  { ticker: 'SONACOMS', name: 'Sona BLW Precision Forgings Ltd.', price: 452.50, change: 0.86, marketCap: '281B', industry: 'Automobile', indices: ['BSE SMALLCAP'] },
  { ticker: 'EMCURE', name: 'Emcure Pharmaceuticals Ltd.', price: 1454.60, change: 0.07, marketCap: '276B', industry: 'Healthcare', indices: ['BSE SMALLCAP'] },
  { ticker: 'TATATECH', name: 'Tata Technologies Ltd.', price: 663.70, change: -0.40, marketCap: '269B', industry: 'Information Technology', indices: ['BSE SMALLCAP'] },
  { ticker: 'INVENTURUS', name: 'Inventurus Knowledge Solutions Ltd.', price: 1556.80, change: 0.03, marketCap: '267B', industry: 'Information Technology', indices: ['BSE SMALLCAP'] },
  { ticker: 'BANDHANBNK', name: 'Bandhan Bank Ltd.', price: 163.10, change: -1.48, marketCap: '263B', industry: 'Banking', indices: ['BSE SMALLCAP'] },
  { ticker: 'STARHEALTH', name: 'Star Health and Allied Insurance Company Ltd.', price: 436.85, change: -1.69, marketCap: '258B', industry: 'Financial Services', indices: ['BSE SMALLCAP'] },
  { ticker: 'PEL', name: 'Piramal Enterprises Ltd.', price: 1121.10, change: -0.65, marketCap: '254B', industry: 'Financial Services', indices: ['BSE SMALLCAP'] },
  { ticker: 'EMAMILTD', name: 'Emami Ltd.', price: 580.00, change: -0.42, marketCap: '254B', industry: 'FMCG', indices: ['BSE SMALLCAP'] },
  { ticker: 'BAYERCROP', name: 'Bayer CropScience Ltd.', price: 5655.70, change: 0.04, marketCap: '254B', industry: 'Agro Chemicals', indices: ['BSE SMALLCAP'] },
  { ticker: 'DEEPAKNTR', name: 'Deepak Nitrite Ltd.', price: 1831.50, change: -2.19, marketCap: '253B', industry: 'Chemicals', indices: ['BSE SMALLCAP'] },
  { ticker: 'RAMCOCEM', name: 'The Ramco Cements Ltd.', price: 1065.30, change: -0.12, marketCap: '252B', industry: 'Cement', indices: ['BSE SMALLCAP'] },
  { ticker: 'SUNTV', name: 'Sun TV Network Ltd.', price: 573.45, change: -2.12, marketCap: '227B', industry: 'Media & Entertainment', indices: ['BSE SMALLCAP'] },
  { ticker: 'CROMPTON', name: 'Crompton Greaves Consumer Electricals Ltd.', price: 319.90, change: 0.41, marketCap: '206B', industry: 'Consumer Durables', indices: ['BSE SMALLCAP'] },
  { ticker: 'CASTROLIND', name: 'Castrol India Ltd.', price: 205.85, change: -1.08, marketCap: '203B', industry: 'Oil & Gas', indices: ['BSE SMALLCAP'] },
  { ticker: 'PSB', name: 'Punjab & Sind Bank', price: 28.14, change: -0.18, marketCap: '199B', industry: 'Banking', indices: ['BSE SMALLCAP'] },
  { ticker: 'FIRSTCRY', name: 'Firstcry (Brainbees Solutions) Ltd.', price: 369.85, change: -1.31, marketCap: '193B', industry: 'Consumer Services', indices: ['BSE SMALLCAP'] },
  { ticker: 'KANSAINER', name: 'Kansai Nerolac Paints Ltd.', price: 236.10, change: -0.08, marketCap: '190B', industry: 'Chemicals', indices: ['BSE SMALLCAP'] },
  { ticker: 'OLA', name: 'Ola Electric Mobility Ltd.', price: 41.32, change: 2.00, marketCap: '182B', industry: 'Automobile', indices: ['BSE SMALLCAP'] },
  { ticker: 'VEDANT', name: 'Vedant Fashions Ltd.', price: 743.80, change: 0.67, marketCap: '181B', industry: 'Textiles', indices: ['BSE SMALLCAP'] },
  { ticker: 'WHIRLPOOL', name: 'Whirlpool of India Ltd.', price: 1239.30, change: -0.20, marketCap: '157B', industry: 'Consumer Durables', indices: ['BSE SMALLCAP'] },
  { ticker: 'AARTIIND', name: 'Aarti Industries Ltd.', price: 375.90, change: -1.82, marketCap: '136B', industry: 'Chemicals', indices: ['BSE SMALLCAP'] },
  { ticker: 'CLEAN', name: 'Clean Science and Technology Ltd.', price: 1187.30, change: -3.46, marketCap: '125B', industry: 'Chemicals', indices: ['BSE SMALLCAP'] },
  { ticker: 'ZEEL', name: 'Zee Entertainment Enterprises Ltd.', price: 116.20, change: -0.47, marketCap: '112B', industry: 'Media & Entertainment', indices: ['BSE SMALLCAP'] },
  { ticker: 'RELAXO', name: 'Relaxo Footwears Ltd.', price: 437.65, change: 1.09, marketCap: '109B', industry: 'Consumer Durables', indices: ['BSE SMALLCAP'] },
  { ticker: 'ABFRL', name: 'Aditya Birla Fashion and Retail Ltd.', price: 75.01, change: 0.41, marketCap: '92B', industry: 'Textiles', indices: ['BSE SMALLCAP'] },
  { ticker: 'AJANTPHARM', name: 'Ajanta Pharma Ltd.', price: 2678.80, change: 0.40, marketCap: '32B', industry: 'Healthcare', indices: ['BSE SMALLCAP'] },
];

export const finniftyStocks = [
  { ticker: 'AXISBANK', name: 'Axis Bank', price: 1068.20, change: 0.21, marketCap: '3.31T', industry: 'Financial Services', indices: ['FINNIFTY', 'NIFTY 50', 'SENSEX 30', 'BANK NIFTY'] },
  { ticker: 'BAJFINANCE', name: 'Bajaj Finance', price: 861.45, change: 0.17, marketCap: '5.35T', industry: 'Financial Services', indices: ['FINNIFTY', 'NIFTY 50', 'SENSEX 30'] },
  { ticker: 'BAJAJFINSV', name: 'Bajaj Finserv', price: 1925.10, change: 0.56, marketCap: '3.08T', industry: 'Financial Services', indices: ['FINNIFTY', 'NIFTY 50', 'SENSEX 30'] },
  { ticker: 'CHOLAFIN', name: 'Cholamandalam Investment', price: 1461.50, change: 0.07, marketCap: '1.23T', industry: 'Financial Services', indices: ['FINNIFTY', 'NIFTY NEXT 50'] },
  { ticker: 'HDFCAMC', name: 'HDFC AMC', price: 5491.00, change: 0.17, marketCap: '1.17T', industry: 'Financial Services', indices: ['FINNIFTY'] },
  { ticker: 'HDFCBANK', name: 'HDFC Bank', price: 1991.10, change: 0.55, marketCap: '15.27T', industry: 'Financial Services', indices: ['FINNIFTY', 'NIFTY 50', 'SENSEX 30', 'BANK NIFTY'] },
  { ticker: 'HDFCLIFE', name: 'HDFC Life Insurance', price: 788.75, change: 1.56, marketCap: '1.70T', industry: 'Financial Services', indices: ['FINNIFTY', 'NIFTY 50'] },
  { ticker: 'ICICIBANK', name: 'ICICI Bank', price: 1427.30, change: 0.46, marketCap: '10.18T', industry: 'Financial Services', indices: ['FINNIFTY', 'NIFTY 50', 'SENSEX 30', 'BANK NIFTY'] },
  { ticker: 'ICICIGI', name: 'ICICI Lombard General Insurance', price: 1898.30, change: -0.75, marketCap: '942B', industry: 'Financial Services', indices: ['FINNIFTY', 'NIFTY NEXT 50'] },
  { ticker: 'ICICIPRULI', name: 'ICICI Prudential Life Insurance', price: 626.60, change: 0.85, marketCap: '906B', industry: 'Financial Services', indices: ['FINNIFTY', 'NIFTY NEXT 50'] },
  { ticker: 'JIOFIN', name: 'Jio Financial Services', price: 327.40, change: -0.97, marketCap: '2.08T', industry: 'Financial Services', indices: ['FINNIFTY'] },
  { ticker: 'KOTAKBANK', name: 'Kotak Bank', price: 1978.20, change: -0.48, marketCap: '3.93T', industry: 'Financial Services', indices: ['FINNIFTY', 'NIFTY 50', 'SENSEX 30', 'BANK NIFTY'] },
  { ticker: 'LICHSGFIN', name: 'LIC Housing Finance', price: 569.25, change: -0.89, marketCap: '313B', industry: 'Financial Services', indices: ['FINNIFTY'] },
  { ticker: 'MUTHOOTFIN', name: 'Muthoot Finance', price: 2757.40, change: 9.86, marketCap: '1.11T', industry: 'Financial Services', indices: ['FINNIFTY', 'BSE MIDCAP', 'BSE SMALLCAP'] },
  { ticker: 'PFC', name: 'Power Finance Corporation', price: 416.50, change: -0.30, marketCap: '1.37T', industry: 'Financial Services', indices: ['FINNIFTY', 'NIFTY NEXT 50'] },
  { ticker: 'RECLTD', name: 'REC', price: 381.55, change: -1.45, marketCap: '1.00T', industry: 'Financial Services', indices: ['FINNIFTY', 'NIFTY NEXT 50'] },
  { ticker: 'SBICARD', name: 'SBI Cards', price: 789.35, change: -0.09, marketCap: '751B', industry: 'Financial Services', indices: ['FINNIFTY'] },
  { ticker: 'SBILIFE', name: 'SBI Life Insurance', price: 1840.60, change: 0.02, marketCap: '1.84T', industry: 'Financial Services', indices: ['FINNIFTY', 'NIFTY 50'] },
  { ticker: 'SHRIRAMFIN', name: 'Shriram Finance', price: 616.45, change: -0.45, marketCap: '1.16T', industry: 'Financial Services', indices: ['FINNIFTY'] },
  { ticker: 'SBIN', name: 'State Bank of India', price: 826.55, change: 0.57, marketCap: '7.38T', industry: 'Financial Services', indices: ['FINNIFTY', 'NIFTY 50', 'SENSEX 30', 'BANK NIFTY'] },
];

export const niftyITStocks = [
  { ticker: 'TCS', name: 'Tata Consultancy Services', price: 3022.30, change: -0.46, marketCap: '10.93T', industry: 'Information Technology', indices: ['NIFTY IT', 'NIFTY 50', 'SENSEX 30'] },
  { ticker: 'INFY', name: 'Infosys', price: 1447.70, change: 1.48, marketCap: '6.01T', industry: 'Information Technology', indices: ['NIFTY IT', 'NIFTY 50', 'SENSEX 30'] },
  { ticker: 'HCLTECH', name: 'HCL Technologies', price: 1489.80, change: -0.75, marketCap: '4.04T', industry: 'Information Technology', indices: ['NIFTY IT', 'NIFTY 50', 'SENSEX 30'] },
  { ticker: 'WIPRO', name: 'Wipro', price: 246.81, change: 2.14, marketCap: '2.59T', industry: 'Information Technology', indices: ['NIFTY IT', 'NIFTY 50', 'SENSEX 30'] },
  { ticker: 'LTIM', name: 'LTI Mindtree', price: 5108.00, change: -0.13, marketCap: '1.51T', industry: 'Information Technology', indices: ['NIFTY IT', 'NIFTY 50', 'NIFTY NEXT 50'] },
  { ticker: 'TECHM', name: 'Tech Mahindra', price: 1486.70, change: -1.30, marketCap: '1.46T', industry: 'Information Technology', indices: ['NIFTY IT', 'NIFTY 50'] },
  { ticker: 'PERSISTENT', name: 'Persistent Systems', price: 5289.00, change: 0.79, marketCap: '827B', industry: 'Information Technology', indices: ['NIFTY IT', 'BSE MIDCAP', 'BSE SMALLCAP'] },
  { ticker: 'OFSS', name: 'Oracle Financial Services Software', price: 8586.50, change: -0.09, marketCap: '746B', industry: 'Information Technology', indices: ['NIFTY IT'] },
  { ticker: 'COFORGE', name: 'Coforge', price: 1642.00, change: 1.25, marketCap: '549B', industry: 'Information Technology', indices: ['NIFTY IT'] },
  { ticker: 'MPHASIS', name: 'Mphasis', price: 2720.20, change: 0.93, marketCap: '518B', industry: 'Information Technology', indices: ['NIFTY IT'] },
];

export const additionalPopularStocks = [
  { ticker: 'ADANIGREEN', name: 'Adani Green Energy Ltd.', price: 964.1, change: 1.1, marketCap: '1.59T', industry: 'Power', indices: ['NIFTY NEXT 50'] },
  { ticker: 'ADANITRANS', name: 'Adani Transmission Ltd.', price: 890, change: 0.5, marketCap: '1.02T', industry: 'Power', indices: ['BSE SMALLCAP'] },
  { ticker: 'ADVENZYMES', name: 'Advanced Enzyme Technologies Ltd.', price: 380, change: -0.8, marketCap: '42B', industry: 'Healthcare', indices: ['BSE SMALLCAP'] },
  { ticker: 'AEGISCHEM', name: 'Aegis Logistics Ltd.', price: 420, change: 1.3, marketCap: '58B', industry: 'Oil, Gas & Consumable Fuels', indices: ['BSE SMALLCAP'] },
  { ticker: 'AFFLE', name: 'Affle (India) Ltd.', price: 1250, change: 2.1, marketCap: '68B', industry: 'Information Technology', indices: ['BSE SMALLCAP'] },
  { ticker: 'AJANTPHARM', name: 'Ajanta Pharma Ltd.', price: 1850, change: -0.6, marketCap: '225B', industry: 'Healthcare', indices: ['BSE SMALLCAP'] },
  { ticker: 'ALKYLAMINE', name: 'Alkyl Amines Chemicals Ltd.', price: 1850, change: 0.9, marketCap: '95B', industry: 'Chemicals', indices: ['BSE SMALLCAP'] },
  { ticker: 'BOSCHLTD', name: 'Bosch Ltd.', price: 38710, change: -1.6, marketCap: '1.14T', industry: 'Automobile and Auto Components', indices: ['NIFTY NEXT 50'] },
  { ticker: 'TORNTPHARM', name: 'Torrent Pharmaceuticals Ltd.', price: 3548.6, change: 0.4, marketCap: '1.2T', industry: 'Healthcare', indices: ['NIFTY NEXT 50'] },
  { ticker: 'NAUKRI', name: 'Info Edge (India) Ltd.', price: 1333, change: -1.9, marketCap: '863B', industry: 'Consumer Services', indices: ['NIFTY NEXT 50'] },
  { ticker: 'GAIL', name: 'GAIL (India) Ltd.', price: 170.1, change: -0.3, marketCap: '1.12T', industry: 'Oil, Gas & Consumable Fuels', indices: ['NIFTY NEXT 50'] },
  { ticker: 'IOC', name: 'Indian Oil Corporation Ltd.', price: 142.0, change: -1.4, marketCap: '2.0T', industry: 'Oil, Gas & Consumable Fuels', indices: ['NIFTY NEXT 50'] },
  { ticker: 'TATAPOWER', name: 'Tata Power Company Ltd.', price: 382.9, change: 2.1, marketCap: '1.22T', industry: 'Power', indices: ['NIFTY NEXT 50'] },
  { ticker: 'SHREECEM', name: 'Shree Cements Ltd.', price: 30230, change: 1.6, marketCap: '1.09T', industry: 'Construction Materials', indices: ['NIFTY NEXT 50'] },
  { ticker: 'MOTHERSON', name: 'Samvardhana Motherson International Ltd.', price: 95.6, change: -2.0, marketCap: '1.01T', industry: 'Automobile and Auto Components', indices: ['NIFTY NEXT 50'] },
  { ticker: 'HAL', name: 'Hindustan Aeronautics Ltd.', price: 4520, change: 0.1, marketCap: '3.02T', industry: 'Capital Goods', indices: ['NIFTY NEXT 50'] },
  { ticker: 'CANBK', name: 'Canara Bank', price: 106.9, change: -1.3, marketCap: '969B', industry: 'Financial Services', indices: ['NIFTY NEXT 50', 'BANK NIFTY'] },
  { ticker: 'VBL', name: 'Varun Beverages Ltd.', price: 503.2, change: 1.0, marketCap: '1.7T', industry: 'Fast Moving Consumer Goods', indices: ['NIFTY NEXT 50'] },
  { ticker: 'ABB', name: 'ABB India Ltd.', price: 5033, change: -0.7, marketCap: '1.07T', industry: 'Capital Goods', indices: ['NIFTY NEXT 50'] },
  { ticker: 'JINDALSTEL', name: 'Jindal Steel & Power Ltd.', price: 993.4, change: 2.2, marketCap: '1.01T', industry: 'Metals & Mining', indices: ['NIFTY NEXT 50'] },
  { ticker: 'ZYDUSLIFE', name: 'Zydus Lifesciences Ltd.', price: 935.5, change: -1.1, marketCap: '941B', industry: 'Healthcare', indices: ['NIFTY NEXT 50'] },
  { ticker: 'TVSMOTOR', name: 'TVS Motor Company Ltd.', price: 2960.4, change: 1.4, marketCap: '1.41T', industry: 'Automobile and Auto Components', indices: ['NIFTY NEXT 50'] },
  { ticker: 'LODHA', name: 'Macrotech Developers Ltd.', price: 1215.7, change: -2.3, marketCap: '1.21T', industry: 'Realty', indices: ['NIFTY NEXT 50'] },
  { ticker: 'JSWENERGY', name: 'JSW Energy Ltd.', price: 522.7, change: 0.6, marketCap: '913B', industry: 'Power', indices: ['NIFTY NEXT 50'] },
  { ticker: 'CGPOWER', name: 'CG Power and Industrial Solutions Ltd.', price: 677.3, change: -1.5, marketCap: '1.07T', industry: 'Capital Goods', indices: ['NIFTY NEXT 50'] },
];

const uniqueStocks = new Map();
[...nifty50Stocks, ...sensexStocks, ...bankNiftyStocks, ...niftyNext50Stocks, ...bseMidcapStocks, ...bseSmallCapStocks, ...finniftyStocks, ...additionalPopularStocks].forEach(stock => {
  if (!uniqueStocks.has(stock.ticker)) {
    uniqueStocks.set(stock.ticker, stock);
  } else {
    const existingStock = uniqueStocks.get(stock.ticker);
    stock.indices.forEach(index => {
      if (!existingStock.indices.includes(index)) {
        existingStock.indices.push(index);
      }
    });
  }
});

export const allStocks = Array.from(uniqueStocks.values());

export const industries = [...new Set(allStocks.map(stock => stock.industry))];

export const indices = {
  nifty: { name: 'NIFTY 50', value: 22547.65, change: 0.85 },
  sensex: { name: 'SENSEX 30', value: 74119.39, change: 0.72 },
  bankNifty: { name: 'BANK NIFTY', value: 48023.45, change: 1.12 },
  niftyNext50: { name: 'NIFTY NEXT 50', value: 66234.78, change: 0.48 },
  finnifty: { name: 'FINNIFTY', value: 19867.23, change: 0.93 },
  bseMidcap: { name: 'BSE MIDCAP', value: 45234.56, change: 0.67 },
  bseSmallcap: { name: 'BSE SMALLCAP', value: 28967.89, change: 0.34 },
  niftyIT: { name: 'NIFTY IT', value: 34567.89, change: -0.23 },
};

export type Stock = (typeof allStocks)[0] & {
  profile?: string;
  peRatio?: number;
  eps?: number;
  dividendYield?: number;
  fiftyTwoWeekHigh?: number;
  fiftyTwoWeekLow?: number;
  news?: { title: string; source: string; date: string }[];
};
export type Index = (typeof indices);