import React from 'react';
import { AlertCircle } from 'lucide-react';

interface AIDisclaimerProps {
  variant?: 'default' | 'compact' | 'inline';
  className?: string;
  show?: boolean;
  context?: 'risk-assessment' | 'general-analysis' | 'investment-advice' | 'fraud-detection';
}

const AIDisclaimer: React.FC<AIDisclaimerProps> = ({ 
  variant = 'default', 
  className = '', 
  show = true,
  context = 'general-analysis'
}) => {
  if (!show) return null;

  const disclaimerText = {
    'risk-assessment': {
      title: 'AI-Generated Risk Assessment Disclaimer',
      content: 'This risk assessment is generated by AI analysis of financial data and should not be considered as professional investment advice. Please conduct your own research and consult with qualified financial advisors before making investment decisions. Past performance does not guarantee future results.'
    },
    'general-analysis': {
      title: 'AI-Generated Analysis Disclaimer', 
      content: 'This analysis is generated by artificial intelligence and is for educational purposes only. It should not be considered as professional financial or investment advice. Always consult qualified financial advisors and conduct your own research before making investment decisions.'
    },
    'investment-advice': {
      title: 'Investment Advisory Disclaimer',
      content: 'This content is generated by AI for educational purposes only and does not constitute professional investment advice. We are not SEBI registered investment advisors. Please verify all information independently and consult with qualified, SEBI-registered financial advisors before making investment decisions.'
    },
    'fraud-detection': {
      title: 'AI Detection System Disclaimer',
      content: 'Our AI fraud detection system is designed to identify potential suspicious patterns but may not catch all fraudulent activities. This analysis is for informational purposes only. Always exercise your own judgment and report suspected fraud to appropriate authorities including SEBI.'
    }
  };

  const currentDisclaimer = disclaimerText[context];

  if (variant === 'inline') {
    return (
      <span className={`text-xs text-gray-500 inline ${className}`}>
        ⚠️ AI-generated content - not financial advice
      </span>
    );
  }

  if (variant === 'compact') {
    return (
      <div className={`flex items-start gap-2 text-xs text-gray-600 bg-gray-50 p-2 rounded border-l-2 border-yellow-400 ${className}`}>
        <AlertCircle className="w-3 h-3 mt-0.5 flex-shrink-0 text-yellow-600" />
        <div>
          <strong>AI Disclaimer:</strong> This is AI-generated content for educational purposes only. 
          Not professional financial advice. Consult qualified advisors before investing.
        </div>
      </div>
    );
  }

  return (
    <div className={`bg-yellow-50 border-l-4 border-yellow-400 p-4 rounded-r-lg ${className}`}>
      <div className="flex items-start">
        <AlertCircle className="w-5 h-5 text-yellow-600 mt-0.5 mr-3 flex-shrink-0" />
        <div>
          <h4 className="text-sm font-semibold text-yellow-800 mb-1">
            {currentDisclaimer.title}
          </h4>
          <p className="text-sm text-yellow-700 leading-relaxed">
            {currentDisclaimer.content}
          </p>
          <div className="mt-2 pt-2 border-t border-yellow-200">
            <p className="text-xs text-yellow-600">
              <strong>SEBI Advisory:</strong> Verify all investment advisors on the official SEBI website before taking advice. 
              Report suspicious activities to SEBI at{' '}
              <a href="https://scores.sebi.gov.in/" target="_blank" rel="noopener noreferrer" 
                 className="underline hover:text-yellow-800">
                scores.sebi.gov.in
              </a>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AIDisclaimer;
